name: Spin up Vercel App
description: 'Deploys the Vercel app and runs end-to-end tests against it'
inputs:
  vercel-token:
    required: true
    description: 'Vercel token to deploy the app'
  PINECONE_API_KEY:
    required: true
    description: 'Pinecone API key to send requests to the Vercel app'

runs:
  using: 'composite'
  steps:
    - name: Check out current repository (pinecone-ts-client)
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Build pinecone-ts-client code
      run: npm install && npm run build
      shell: bash

    - name: Package pinecone-ts-client code
      run: npm pack && echo "Step 4, running npm pack"
      shell: bash

    - name: Clone Vercel app
      uses: GuillaumeFalourd/clone-github-repo-action@main
      with:
        owner: 'pinecone-io'
        repository: 'ts-client-test-external-app'
        branch: 'main'

    - name: Install Vercel app dependencies
      run: cd ts-client-test-external-app && npm install
      shell: bash

    - name: Move packed ts-client code into the Vercel app dir
      run: cd ts-client-test-external-app && mv ../pinecone-database-pinecone-*.tgz .
      shell: bash

    - name: Install ts-client code into the Vercel app's package.json file
      run: |
        cd ts-client-test-external-app
        npm install pinecone-database-pinecone-*.tgz
      shell: bash
    
    - name: Verify installation and show package info
      run: |
        cd ts-client-test-external-app
        echo "=== Installed @pinecone-database/pinecone version ==="
        npm list @pinecone-database/pinecone || true
        echo "=== package.json dependencies ==="
        cat package.json | grep -A 10 '"dependencies"' || true
      shell: bash

    - name: Install Vercel CLI and (re)deploy the app
      run: |
        cd ts-client-test-external-app
        npm install --global vercel@latest
        vercel --token ${{ inputs.vercel-token }} --scope pinecone-io --yes
        vercel pull --yes --token ${{ inputs.vercel-token }} --scope pinecone-io
        
        # Run build with explicit error handling
        echo "Starting Vercel build..."
        if ! vercel build --token ${{ inputs.vercel-token }} --scope pinecone-io --debug 2>&1; then
          echo "❌ Vercel build failed!"
          echo "Checking for build logs..."
          
          # Try to find and display Next.js build logs
          if [ -f ".vercel/output/static/_logs/build.log" ]; then
            echo "=== Build Log ==="
            cat .vercel/output/static/_logs/build.log
          fi
          
          # Display any error logs in .next
          if [ -d ".next" ]; then
            echo "=== .next directory contents ==="
            ls -la .next/ || true
            if [ -f ".next/trace" ]; then
              echo "=== Next.js trace ==="
              cat .next/trace || true
            fi
          fi
          
          # Display npm logs if they exist
          if [ -f "npm-debug.log" ]; then
            echo "=== NPM Debug Log ==="
            cat npm-debug.log
          fi
          
          exit 1
        fi
        
        echo "Build successful, deploying to production..."
        vercel --token ${{ inputs.vercel-token }} --scope pinecone-io --prod
      shell: bash

    - name: Run end-to-end tests against the deployed Vercel app with assertResponse.ts
      run: |
        echo "=== Running end-to-end tests ==="
        if ! npx tsx ts-external-app-test/assertResponse.ts; then
          echo "❌ End-to-end tests failed!"
          echo "Deployment URL should be accessible at the Vercel preview/production URL shown above"
          exit 1
        fi
        echo "✅ End-to-end tests passed!"
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
      shell: bash
