name: Spin up Vercel App
description: 'Deploys the Vercel app and runs end-to-end tests against it'
inputs:
  vercel-token:
    required: true
    description: 'Vercel token to deploy the app'
  PINECONE_API_KEY:
    required: true
    description: 'Pinecone API key to send requests to the Vercel app'

runs:
  using: 'composite'
  steps:
    - name: Check out current repository (pinecone-ts-client)
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18.20.3'

    - name: Build pinecone-ts-client code
      run: npm install && npm run build
      shell: bash

    - name: Package pinecone-ts-client code
      run: npm pack && echo "Step 4, running npm pack"
      shell: bash

    - name: Clone Vercel app
      uses: GuillaumeFalourd/clone-github-repo-action@main
      with:
        owner: 'pinecone-io'
        repository: 'ts-client-test-external-app'
        branch: 'main'

    - name: Install Vercel app dependencies
      run: cd ts-client-test-external-app && npm install
      shell: bash

    - name: Move packed ts-client code into the Vercel app dir
      run: cd ts-client-test-external-app && mv ../pinecone-database-pinecone-*.tgz .
      shell: bash

    - name: Install ts-client code into the Vercel app's package.json file
      run: |
        cd ts-client-test-external-app
        npm install pinecone-database-pinecone-*.tgz
      shell: bash

    - name: Install Vercel CLI and (re)deploy the app
      run: |
        cd ts-client-test-external-app
        npm install --global vercel@latest
        vercel --token ${{ inputs.vercel-token }} --yes
        vercel pull --yes --token ${{ inputs.vercel-token }}
        vercel build --token ${{ inputs.vercel-token }}
        vercel --token ${{ inputs.vercel-token }} --prod
      shell: bash

    - name: Run end-to-end tests against the deployed Vercel app with assertResponse.ts
      run: |
        npx tsx ts-external-app-test/assertResponse.ts
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
      shell: bash
