name: 'Update example app'
description: 'Bump example app to latest version of the node client'
inputs:
  repository_org:
    description: 'Example: pinecone-io'
    default: 'pinecone-io'
  repository_name:
    description: 'Example: semantic-search-example'
  client_version:
    description: 'Dependency version to bump to'
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Checkout example app
      uses: actions/checkout@v4
      with:
        repository: '${{ inputs.repository_org }}/${{ inputs.repository_name }}'
        path: ${{ inputs.repository_name }}
    - name: Update client version
      id: install
      shell: bash
      run: |
        cd ${{ inputs.repository_name }}
        npm install --no-cache
        npm install "@pinecone-database/pinecone@${{ inputs.client_version }}"
        cat package.json
        pineconeVersion=$(jq -r '.dependencies."@pinecone-database/pinecone"' package.json | sed 's/[\^\~]//')
        echo "pineconeVersion=$pineconeVersion" >> $GITHUB_OUTPUT
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        add-paths: |
          package.json
          package-lock.json
        commit-message: 'Update node client dependency to ${{ steps.install.outputs.pineconeVersion }}'
        committer: SDK Bump Bot <clients@pinecone.io>
        base: main
        branch: dep-update/@pinecone-database/pinecone@${{ steps.install.outputs.pineconeVersion }}
        title: 'Update @pinecone-database/pinecone to ${{ steps.install.outputs.pineconeVersion }}'
        body: |
          ## Update Pinecone SDK version

          - This PR was generated by a CI job in the pinecone-ts-client repository
        labels: |
          automated pr
        assignees: jhamon
        reviewers: jhamon
        draft: false
