name: 'Setup'
description: 'Node setup, install, and build'
inputs:
  node_version:
    description: 'Node.js version to setup'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup runtime
      uses: ./.github/actions/setup-runtime
      with:
        node_version: ${{ inputs.node_version }}
    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
    - name: Install npm packages
      run: |
        npm ci
      shell: bash
    - name: Build typescript
      run: npm run build
      shell: bash
