name: 'Setup'
description: 'Node setup, install, and build'
inputs:
  pinecone_api_key:
    description: 'API key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
    - name: Install npm packages
      run: |
        npm install --ignore-scripts
      shell: bash
    - name: Build typescript
      run: npm run build
      shell: bash
