/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApproximatedConfig
 */
export interface ApproximatedConfig {
    /**
     * 
     * @type {number}
     * @memberof ApproximatedConfig
     */
    kBits?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApproximatedConfig
     */
    hybrid?: boolean;
}

/**
 * Check if a given object implements the ApproximatedConfig interface.
 */
export function instanceOfApproximatedConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApproximatedConfigFromJSON(json: any): ApproximatedConfig {
    return ApproximatedConfigFromJSONTyped(json, false);
}

export function ApproximatedConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApproximatedConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kBits': !exists(json, 'k_bits') ? undefined : json['k_bits'],
        'hybrid': !exists(json, 'hybrid') ? undefined : json['hybrid'],
    };
}

export function ApproximatedConfigToJSON(value?: ApproximatedConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'k_bits': value.kBits,
        'hybrid': value.hybrid,
    };
}

