/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Admin API
 * Provides an API for managing a Pinecone organization and its resources, including projects, API keys, organization users and invites, service accounts, and role bindings. 
 *
 * The version of the OpenAPI document: 2026-04
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateRoleBindingRequest,
  ErrorResponse,
  RoleBinding,
  RoleBindingList,
} from '../models/index';
import {
    CreateRoleBindingRequestFromJSON,
    CreateRoleBindingRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RoleBindingFromJSON,
    RoleBindingToJSON,
    RoleBindingListFromJSON,
    RoleBindingListToJSON,
} from '../models/index';

export interface CreateRoleBindingOperationRequest {
    xPineconeApiVersion: string;
    createRoleBindingRequest: CreateRoleBindingRequest;
}

export interface DeleteRoleBindingRequest {
    xPineconeApiVersion: string;
    roleBindingId: string;
}

export interface FetchRoleBindingRequest {
    xPineconeApiVersion: string;
    roleBindingId: string;
}

export interface ListRoleBindingsRequest {
    xPineconeApiVersion: string;
    principalType?: string;
    principalId?: string;
    resourceType?: string;
    resourceId?: string;
    role?: string;
    limit?: number;
    paginationToken?: string;
}

/**
 * 
 */
export class RoleBindingsApi extends runtime.BaseAPI {

    /**
     * Grant a role to a principal at an organization or project scope. 
     * Create a role binding
     */
    async createRoleBindingRaw(requestParameters: CreateRoleBindingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleBinding>> {
        if (requestParameters.xPineconeApiVersion === null || requestParameters.xPineconeApiVersion === undefined) {
            throw new runtime.RequiredError('xPineconeApiVersion','Required parameter requestParameters.xPineconeApiVersion was null or undefined when calling createRoleBinding.');
        }

        if (requestParameters.createRoleBindingRequest === null || requestParameters.createRoleBindingRequest === undefined) {
            throw new runtime.RequiredError('createRoleBindingRequest','Required parameter requestParameters.createRoleBindingRequest was null or undefined when calling createRoleBinding.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xPineconeApiVersion !== undefined && requestParameters.xPineconeApiVersion !== null) {
            headerParameters['X-Pinecone-Api-Version'] = String(requestParameters.xPineconeApiVersion);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/role-bindings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRoleBindingRequestToJSON(requestParameters.createRoleBindingRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleBindingFromJSON(jsonValue));
    }

    /**
     * Grant a role to a principal at an organization or project scope. 
     * Create a role binding
     */
    async createRoleBinding(requestParameters: CreateRoleBindingOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleBinding> {
        const response = await this.createRoleBindingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a role binding; permissions are revoked when the deletion completes. 
     * Delete a role binding
     */
    async deleteRoleBindingRaw(requestParameters: DeleteRoleBindingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.xPineconeApiVersion === null || requestParameters.xPineconeApiVersion === undefined) {
            throw new runtime.RequiredError('xPineconeApiVersion','Required parameter requestParameters.xPineconeApiVersion was null or undefined when calling deleteRoleBinding.');
        }

        if (requestParameters.roleBindingId === null || requestParameters.roleBindingId === undefined) {
            throw new runtime.RequiredError('roleBindingId','Required parameter requestParameters.roleBindingId was null or undefined when calling deleteRoleBinding.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xPineconeApiVersion !== undefined && requestParameters.xPineconeApiVersion !== null) {
            headerParameters['X-Pinecone-Api-Version'] = String(requestParameters.xPineconeApiVersion);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/role-bindings/{role_binding_id}`.replace(`{${"role_binding_id"}}`, encodeURIComponent(String(requestParameters.roleBindingId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a role binding; permissions are revoked when the deletion completes. 
     * Delete a role binding
     */
    async deleteRoleBinding(requestParameters: DeleteRoleBindingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRoleBindingRaw(requestParameters, initOverrides);
    }

    /**
     * Get a role binding in the caller\'s organization by ID. 
     * Get role binding details
     */
    async fetchRoleBindingRaw(requestParameters: FetchRoleBindingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleBinding>> {
        if (requestParameters.xPineconeApiVersion === null || requestParameters.xPineconeApiVersion === undefined) {
            throw new runtime.RequiredError('xPineconeApiVersion','Required parameter requestParameters.xPineconeApiVersion was null or undefined when calling fetchRoleBinding.');
        }

        if (requestParameters.roleBindingId === null || requestParameters.roleBindingId === undefined) {
            throw new runtime.RequiredError('roleBindingId','Required parameter requestParameters.roleBindingId was null or undefined when calling fetchRoleBinding.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xPineconeApiVersion !== undefined && requestParameters.xPineconeApiVersion !== null) {
            headerParameters['X-Pinecone-Api-Version'] = String(requestParameters.xPineconeApiVersion);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/role-bindings/{role_binding_id}`.replace(`{${"role_binding_id"}}`, encodeURIComponent(String(requestParameters.roleBindingId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleBindingFromJSON(jsonValue));
    }

    /**
     * Get a role binding in the caller\'s organization by ID. 
     * Get role binding details
     */
    async fetchRoleBinding(requestParameters: FetchRoleBindingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleBinding> {
        const response = await this.fetchRoleBindingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List role bindings in the caller\'s organization, optionally filtered by principal, resource, and role. 
     * List role bindings
     */
    async listRoleBindingsRaw(requestParameters: ListRoleBindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleBindingList>> {
        if (requestParameters.xPineconeApiVersion === null || requestParameters.xPineconeApiVersion === undefined) {
            throw new runtime.RequiredError('xPineconeApiVersion','Required parameter requestParameters.xPineconeApiVersion was null or undefined when calling listRoleBindings.');
        }

        const queryParameters: any = {};

        if (requestParameters.principalType !== undefined) {
            queryParameters['principal_type'] = requestParameters.principalType;
        }

        if (requestParameters.principalId !== undefined) {
            queryParameters['principal_id'] = requestParameters.principalId;
        }

        if (requestParameters.resourceType !== undefined) {
            queryParameters['resource_type'] = requestParameters.resourceType;
        }

        if (requestParameters.resourceId !== undefined) {
            queryParameters['resource_id'] = requestParameters.resourceId;
        }

        if (requestParameters.role !== undefined) {
            queryParameters['role'] = requestParameters.role;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.paginationToken !== undefined) {
            queryParameters['paginationToken'] = requestParameters.paginationToken;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xPineconeApiVersion !== undefined && requestParameters.xPineconeApiVersion !== null) {
            headerParameters['X-Pinecone-Api-Version'] = String(requestParameters.xPineconeApiVersion);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/role-bindings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleBindingListFromJSON(jsonValue));
    }

    /**
     * List role bindings in the caller\'s organization, optionally filtered by principal, resource, and role. 
     * List role bindings
     */
    async listRoleBindings(requestParameters: ListRoleBindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleBindingList> {
        const response = await this.listRoleBindingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
