/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone AssistantCtrlPlane Engine API
 * Pinecone AssistantCtrlPlane Engine is a context engine to store and retrieve relevant knowledge  from millions of documents at scale. This API supports creating and managing assistants.
 *
 * The version of the OpenAPI document: v1alpha
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListAssistants401ResponseError } from './ListAssistants401ResponseError';
import {
    ListAssistants401ResponseErrorFromJSON,
    ListAssistants401ResponseErrorFromJSONTyped,
    ListAssistants401ResponseErrorToJSON,
} from './ListAssistants401ResponseError';

/**
 * The response shape used for all error responses.
 * @export
 * @interface ListAssistants401Response
 */
export interface ListAssistants401Response {
    /**
     * The HTTP status code of the error.
     * @type {number}
     * @memberof ListAssistants401Response
     */
    status: number;
    /**
     * 
     * @type {ListAssistants401ResponseError}
     * @memberof ListAssistants401Response
     */
    error: ListAssistants401ResponseError;
}

/**
 * Check if a given object implements the ListAssistants401Response interface.
 */
export function instanceOfListAssistants401Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function ListAssistants401ResponseFromJSON(json: any): ListAssistants401Response {
    return ListAssistants401ResponseFromJSONTyped(json, false);
}

export function ListAssistants401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAssistants401Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'error': ListAssistants401ResponseErrorFromJSON(json['error']),
    };
}

export function ListAssistants401ResponseToJSON(value?: ListAssistants401Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'error': ListAssistants401ResponseErrorToJSON(value.error),
    };
}

