/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Inference API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmbedRequest,
  EmbeddingsList,
  ErrorResponse,
  ModelInfo,
  ModelInfoList,
  RerankRequest,
  RerankResult,
} from '../models/index';
import {
    EmbedRequestFromJSON,
    EmbedRequestToJSON,
    EmbeddingsListFromJSON,
    EmbeddingsListToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ModelInfoFromJSON,
    ModelInfoToJSON,
    ModelInfoListFromJSON,
    ModelInfoListToJSON,
    RerankRequestFromJSON,
    RerankRequestToJSON,
    RerankResultFromJSON,
    RerankResultToJSON,
} from '../models/index';

export interface EmbedOperationRequest {
    xPineconeApiVersion: string;
    embedRequest?: EmbedRequest;
}

export interface GetModelRequest {
    xPineconeApiVersion: string;
    modelName: string;
}

export interface ListModelsRequest {
    xPineconeApiVersion: string;
    type?: string;
    vectorType?: string;
}

export interface RerankOperationRequest {
    xPineconeApiVersion: string;
    rerankRequest?: RerankRequest;
}

/**
 * 
 */
export class InferenceApi extends runtime.BaseAPI {

    /**
     * Generate vector embeddings for input data. This endpoint uses Pinecone\'s [hosted embedding models](https://docs.pinecone.io/guides/index-data/create-an-index#embedding-models).
     * Generate vectors
     */
    async embedRaw(requestParameters: EmbedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmbeddingsList>> {
        if (requestParameters.xPineconeApiVersion === null || requestParameters.xPineconeApiVersion === undefined) {
            throw new runtime.RequiredError('xPineconeApiVersion','Required parameter requestParameters.xPineconeApiVersion was null or undefined when calling embed.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xPineconeApiVersion !== undefined && requestParameters.xPineconeApiVersion !== null) {
            headerParameters['X-Pinecone-Api-Version'] = String(requestParameters.xPineconeApiVersion);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = this.configuration.apiKey("Api-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/embed`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmbedRequestToJSON(requestParameters.embedRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmbeddingsListFromJSON(jsonValue));
    }

    /**
     * Generate vector embeddings for input data. This endpoint uses Pinecone\'s [hosted embedding models](https://docs.pinecone.io/guides/index-data/create-an-index#embedding-models).
     * Generate vectors
     */
    async embed(requestParameters: EmbedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmbeddingsList> {
        const response = await this.embedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a description of a model hosted by Pinecone.   You can use hosted models as an integrated part of Pinecone operations or for standalone embedding and reranking. For more details, see [Vector embedding](https://docs.pinecone.io/guides/index-data/indexing-overview#vector-embedding) and [Rerank results](https://docs.pinecone.io/guides/search/rerank-results).
     * Describe a model
     */
    async getModelRaw(requestParameters: GetModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelInfo>> {
        if (requestParameters.xPineconeApiVersion === null || requestParameters.xPineconeApiVersion === undefined) {
            throw new runtime.RequiredError('xPineconeApiVersion','Required parameter requestParameters.xPineconeApiVersion was null or undefined when calling getModel.');
        }

        if (requestParameters.modelName === null || requestParameters.modelName === undefined) {
            throw new runtime.RequiredError('modelName','Required parameter requestParameters.modelName was null or undefined when calling getModel.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xPineconeApiVersion !== undefined && requestParameters.xPineconeApiVersion !== null) {
            headerParameters['X-Pinecone-Api-Version'] = String(requestParameters.xPineconeApiVersion);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = this.configuration.apiKey("Api-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/models/{model_name}`.replace(`{${"model_name"}}`, encodeURIComponent(String(requestParameters.modelName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelInfoFromJSON(jsonValue));
    }

    /**
     * Get a description of a model hosted by Pinecone.   You can use hosted models as an integrated part of Pinecone operations or for standalone embedding and reranking. For more details, see [Vector embedding](https://docs.pinecone.io/guides/index-data/indexing-overview#vector-embedding) and [Rerank results](https://docs.pinecone.io/guides/search/rerank-results).
     * Describe a model
     */
    async getModel(requestParameters: GetModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelInfo> {
        const response = await this.getModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List the embedding and reranking models hosted by Pinecone.   You can use hosted models as an integrated part of Pinecone operations or for standalone embedding and reranking. For more details, see [Vector embedding](https://docs.pinecone.io/guides/index-data/indexing-overview#vector-embedding) and [Rerank results](https://docs.pinecone.io/guides/search/rerank-results).
     * List available models
     */
    async listModelsRaw(requestParameters: ListModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelInfoList>> {
        if (requestParameters.xPineconeApiVersion === null || requestParameters.xPineconeApiVersion === undefined) {
            throw new runtime.RequiredError('xPineconeApiVersion','Required parameter requestParameters.xPineconeApiVersion was null or undefined when calling listModels.');
        }

        const queryParameters: any = {};

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        if (requestParameters.vectorType !== undefined) {
            queryParameters['vector_type'] = requestParameters.vectorType;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xPineconeApiVersion !== undefined && requestParameters.xPineconeApiVersion !== null) {
            headerParameters['X-Pinecone-Api-Version'] = String(requestParameters.xPineconeApiVersion);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = this.configuration.apiKey("Api-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/models`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelInfoListFromJSON(jsonValue));
    }

    /**
     * List the embedding and reranking models hosted by Pinecone.   You can use hosted models as an integrated part of Pinecone operations or for standalone embedding and reranking. For more details, see [Vector embedding](https://docs.pinecone.io/guides/index-data/indexing-overview#vector-embedding) and [Rerank results](https://docs.pinecone.io/guides/search/rerank-results).
     * List available models
     */
    async listModels(requestParameters: ListModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelInfoList> {
        const response = await this.listModelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rerank results according to their relevance to a query.  For guidance and examples, see [Rerank results](https://docs.pinecone.io/guides/search/rerank-results).
     * Rerank results
     */
    async rerankRaw(requestParameters: RerankOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RerankResult>> {
        if (requestParameters.xPineconeApiVersion === null || requestParameters.xPineconeApiVersion === undefined) {
            throw new runtime.RequiredError('xPineconeApiVersion','Required parameter requestParameters.xPineconeApiVersion was null or undefined when calling rerank.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xPineconeApiVersion !== undefined && requestParameters.xPineconeApiVersion !== null) {
            headerParameters['X-Pinecone-Api-Version'] = String(requestParameters.xPineconeApiVersion);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Api-Key"] = this.configuration.apiKey("Api-Key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/rerank`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RerankRequestToJSON(requestParameters.rerankRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RerankResultFromJSON(jsonValue));
    }

    /**
     * Rerank results according to their relevance to a query.  For guidance and examples, see [Rerank results](https://docs.pinecone.io/guides/search/rerank-results).
     * Rerank results
     */
    async rerank(requestParameters: RerankOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RerankResult> {
        const response = await this.rerankRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
