/**
 * Pinecone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class IndexMetaDatabaseStatus {
    'ready'?: boolean;
    'state'?: IndexMetaDatabaseStatus.StateEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ready",
            "baseName": "ready",
            "type": "boolean"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "IndexMetaDatabaseStatus.StateEnum"
        }    ];

    static getAttributeTypeMap() {
        return IndexMetaDatabaseStatus.attributeTypeMap;
    }
}

export namespace IndexMetaDatabaseStatus {
    export enum StateEnum {
        Initializing = <any> 'Initializing',
        ScalingUp = <any> 'ScalingUp',
        ScalingDown = <any> 'ScalingDown',
        Terminating = <any> 'Terminating',
        Ready = <any> 'Ready'
    }
}
