/**
 * Pinecone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ScoredVector } from './scoredVector';
import { SingleQueryResults } from './singleQueryResults';

/**
* The response for the `Query` operation. These are the matches found for a particular query vector. The matches are ordered from most similar to least similar.
*/
export class QueryResponse {
    /**
    * DEPRECATED. The results of each query. The order is the same as `QueryRequest.queries`.
    */
    'results'?: Array<SingleQueryResults>;
    /**
    * The matches for the vectors.
    */
    'matches'?: Array<ScoredVector>;
    /**
    * The namespace for the vectors.
    */
    'namespace'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<SingleQueryResults>"
        },
        {
            "name": "matches",
            "baseName": "matches",
            "type": "Array<ScoredVector>"
        },
        {
            "name": "namespace",
            "baseName": "namespace",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return QueryResponse.attributeTypeMap;
    }
}

