name: Spin up Vercel App

inputs:
  vercel-token:
    required: true
  vercel-project-id:
    required: true
  vercel-org-id:
    required: true
  PINECONE_API_KEY:
    required: true
  PINECONE_INDEX:
    required: true
  PINECONE_CLOUD:
    required: true
  PINECONE_REGION:
    required: true
  OPENAI_API_KEY:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out current repository (pinecone-ts-client)
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18.20.3'

    - name: Build pinecone-ts-client code
      run: npm install && npm run build
      shell: bash

    - name: Package pinecone-ts-client code
      run: npm pack
      shell: bash

    - name: Clone Vercel app
      uses: GuillaumeFalourd/clone-github-repo-action@main
      with:
        owner: 'pinecone-io'
        repository: 'pinecone-rag-demo'
        branch: 'main'

    - name: Move package to pinecone-rag-demo
      run: cd pinecone-rag-demo && mv ../pinecone-database-pinecone-*.tgz .
      shell: bash

    - name: Install rag-demo deps
      run: cd pinecone-rag-demo && npm install
      shell: bash

    - name: Install pinecone-ts-client "main" branch code into the Vercel app
      run: cd pinecone-rag-demo && npm install pinecone-database-pinecone-*.tgz
      shell: bash

    - name: Install Vercel CLI
      run: cd pinecone-rag-demo && npm install vercel
      shell: bash

    - name: Pull Vercel Environment Information
      run: |
        cd pinecone-rag-demo
        vercel pull --yes --environment=preview --token=${{ inputs.vercel-token }} --scope=pinecone-io
      env:
        vercel-token: ${{ inputs.vercel-token }}
        vercel-project-id: ${{ inputs.vercel-project-id }}
        vercel-org-id: ${{ inputs.vercel-org-id }}
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        PINECONE_REGION: ${{ inputs.PINECONE_REGION }}
        PINECONE_INDEX: ${{ inputs.PINECONE_INDEX }}
        PINECONE_CLOUD: ${{ inputs.PINECONE_CLOUD }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      shell: bash

#    - name: Build Project Artifacts
#      run: |
#        cd pinecone-rag-demo
#        vercel build --yes --token=${{ inputs.vercel-token }} --scope=pinecone-io
#      env:
#        vercel-token: ${{ inputs.vercel-token }}
#        vercel-project-id: ${{ inputs.vercel-project-id }}
#        vercel-org-id: ${{ inputs.vercel-org-id }}
#        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
#        PINECONE_REGION: ${{ inputs.PINECONE_REGION }}
#        PINECONE_INDEX: ${{ inputs.PINECONE_INDEX }}
#        PINECONE_CLOUD: ${{ inputs.PINECONE_CLOUD }}
#        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
#      shell: bash

    - name: Deploy Project Artifacts to Vercel
      run: |
        cd pinecone-rag-demo
        vercel \
        --build-env vercel-token=${{ inputs.vercel-token }} \
        --build-env PINECONE_API_KEY=${{ inputs.PINECONE_API_KEY }} \
        --build-env PINECONE_REGION=${{ inputs.PINECONE_REGION }} \ 
        --build-env PINECONE_INDEX=${{ inputs.PINECONE_INDEX }} \
        --build-env PINECONE_CLOUD=${{ inputs.PINECONE_CLOUD }} \
        --build-env OPENAI_API_KEY=${{ inputs.OPENAI_API_KEY }} \
        --scope=pinecone-io
#        vercel deploy --prebuilt --token=${{ inputs.vercel-token }} --scope=pinecone-io
      env:
        vercel-token: ${{ inputs.vercel-token }}
        vercel-project-id: ${{ inputs.vercel-project-id }}
        vercel-org-id: ${{ inputs.vercel-org-id }}
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        PINECONE_REGION: ${{ inputs.PINECONE_REGION }}
        PINECONE_INDEX: ${{ inputs.PINECONE_INDEX }}
        PINECONE_CLOUD: ${{ inputs.PINECONE_CLOUD }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      shell: bash
