name: Spin up Vercel App

inputs:
  vercel-token:
    required: true
  vercel-project-id:
    required: true
  vercel-org-id:
    required: true
  PINECONE_API_KEY:
    required: true
  OPENAI_API_KEY:
    required: true
  VERCEL_TEAM_SCOPE:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out current repository (pinecone-ts-client)
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18.20.3'

    - name: Setup Vercel
      uses: amondnet/vercel-action@master
      with:
        vercel-token: ${{ inputs.vercel-token }}
        vercel-project-id: ${{ inputs.vercel-project-id }}
        vercel-org-id: ${{ inputs.vercel-org-id }}
      env:
        vercel-token: ${{ inputs.vercel-token }}
        vercel-project-id: ${{ inputs.vercel-project-id }}
        vercel-org-id: ${{ inputs.vercel-org-id }}

    - name: Build pinecone-ts-client code
      run: npm run build
      shell: bash

    - name: Package pinecone-ts-client code
      run: npm pack
      shell: bash

    - name: Clone Pinecone Vercel app into pinecone-ts-client
      run: |
        git clone git@github.com:pinecone-io/pinecone-rag-demo.git
        cd pinecone-rag-demo
        git pull origin main
      shell: bash

    - name: Move package to pinecone-rag-demo
      run: mv pinecone-database-pinecone-*.tgz .
      shell: bash

    - name: Install Pinecone Vercel app dependencies
      run: npm install
      shell: bash

    - name: Install pinecone-ts-client "main" branch code into the Vercel app
      run: npm install pinecone-database-pinecone-*.tgz
      shell: bash

    - name: Install pnpm
      run: npm install -g pnpm
      shell: bash

    - name: Install rag app dependencies with pnpm
      run: pnpm install
      shell: bash

    - name: Remove linting temporarily
      run: rm -rf .eslintrc.json
      shell: bash

    - name: Build Pinecone Vercel app
      run: pnpm run build
      shell: bash

    - name: Install Vercel CLI
      run: pnpm add -g vercel
      shell: bash

    - name: Create vercel.json file
      run: |
        cd pinecone-rag-demo
        echo '{
          "version": 2,
          "public": false,
          "github": {
            "enabled": false
          },
          "buildCommand": "next build",
          "installCommand": "npm install",
          "framework": "nextjs",
          "functions": {
            "src/app/**/*.{ts,tsx}": {
              "runtime": "edge",
              "includeFiles": "src/app/**/*"
            }
          }
        }' > vercel.json
      shell: bash

    - name: Deploy to Vercel
      env:
        VERCEL_TEAM_SCOPE: ${{ inputs.VERCEL_TEAM_SCOPE }}
        vercel-token: ${{ inputs.vercel-token }}
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        PINECONE_REGION: us-west-2
        PINECONE_INDEX: end-to-end-edge-test
        PINECONE_CLOUD: aws
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      run: vercel --yes --logs --token=$vercel-token --scope=$VERCEL_TEAM_SCOPE
      shell: bash
