/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Admin API
 * Provides an API for managing a Pinecone organization and its resources, including projects, API keys, organization users and invites, service accounts, and role bindings. 
 *
 * The version of the OpenAPI document: 2026-04
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectRequest
 */
export interface CreateProjectRequest {
    /**
     * The name of the new project.
     * @type {string}
     * @memberof CreateProjectRequest
     */
    name: string;
    /**
     * The maximum number of Pods that can be created in the project. Default is `0` (serverless only).
     * @type {number}
     * @memberof CreateProjectRequest
     */
    maxPods?: number;
    /**
     * Whether to force encryption with a customer-managed encryption key (CMEK). Default is `false`.
     * @type {boolean}
     * @memberof CreateProjectRequest
     */
    forceEncryptionWithCmek?: boolean;
}

/**
 * Check if a given object implements the CreateProjectRequest interface.
 */
export function instanceOfCreateProjectRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateProjectRequestFromJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestFromJSONTyped(json, false);
}

export function CreateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'maxPods': !exists(json, 'max_pods') ? undefined : json['max_pods'],
        'forceEncryptionWithCmek': !exists(json, 'force_encryption_with_cmek') ? undefined : json['force_encryption_with_cmek'],
    };
}

export function CreateProjectRequestToJSON(value?: CreateProjectRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'max_pods': value.maxPods,
        'force_encryption_with_cmek': value.forceEncryptionWithCmek,
    };
}

