/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Admin API
 * Provides an API for managing a Pinecone organization and its resources, including projects, API keys, organization users and invites, service accounts, and role bindings. 
 *
 * The version of the OpenAPI document: 2026-04
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An invitation to join the organization.
 * @export
 * @interface Invite
 */
export interface Invite {
    /**
     * The unique ID of the invite.
     * @type {string}
     * @memberof Invite
     */
    id: string;
    /**
     * The email address the invite was sent to.
     * @type {string}
     * @memberof Invite
     */
    email: string;
    /**
     * The lifecycle status of an invite.
     * Possible values: `pending`, `expired`, `processed`. List endpoints return only `pending` and `expired` invites; `processed` is returned only when fetching a single invite by ID.
     * @type {string}
     * @memberof Invite
     */
    status: string;
    /**
     * When the invite expires if not accepted. Default TTL is 7 days. Resending the invite extends this to now plus 7 days. `null` if the invite does not expire.
     * @type {Date}
     * @memberof Invite
     */
    expiresAt?: Date | null;
    /**
     * The date and time the invite was accepted. `null` or omitted while the invite is still pending or expired.
     * @type {Date}
     * @memberof Invite
     */
    processedAt?: Date | null;
    /**
     * The date and time the invite was created.
     * @type {Date}
     * @memberof Invite
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Invite interface.
 */
export function instanceOfInvite(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function InviteFromJSON(json: any): Invite {
    return InviteFromJSONTyped(json, false);
}

export function InviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'status': json['status'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : (json['expires_at'] === null ? null : new Date(json['expires_at'])),
        'processedAt': !exists(json, 'processed_at') ? undefined : (json['processed_at'] === null ? null : new Date(json['processed_at'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function InviteToJSON(value?: Invite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'status': value.status,
        'expires_at': value.expiresAt === undefined ? undefined : (value.expiresAt === null ? null : value.expiresAt.toISOString()),
        'processed_at': value.processedAt === undefined ? undefined : (value.processedAt === null ? null : value.processedAt.toISOString()),
        'created_at': (value.createdAt.toISOString()),
    };
}

