/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Admin API
 * Provides an API for managing a Pinecone organization and its resources, including projects, API keys, organization users and invites, service accounts, and role bindings. 
 *
 * The version of the OpenAPI document: 2026-04
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InviteListPagination } from './InviteListPagination';
import {
    InviteListPaginationFromJSON,
    InviteListPaginationFromJSONTyped,
    InviteListPaginationToJSON,
} from './InviteListPagination';
import type { RoleBinding } from './RoleBinding';
import {
    RoleBindingFromJSON,
    RoleBindingFromJSONTyped,
    RoleBindingToJSON,
} from './RoleBinding';

/**
 * A paginated list of role bindings.
 * @export
 * @interface RoleBindingList
 */
export interface RoleBindingList {
    /**
     * The page of role bindings.
     * @type {Array<RoleBinding>}
     * @memberof RoleBindingList
     */
    data: Array<RoleBinding>;
    /**
     * 
     * @type {InviteListPagination}
     * @memberof RoleBindingList
     */
    pagination?: InviteListPagination | null;
}

/**
 * Check if a given object implements the RoleBindingList interface.
 */
export function instanceOfRoleBindingList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function RoleBindingListFromJSON(json: any): RoleBindingList {
    return RoleBindingListFromJSONTyped(json, false);
}

export function RoleBindingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleBindingList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(RoleBindingFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : InviteListPaginationFromJSON(json['pagination']),
    };
}

export function RoleBindingListToJSON(value?: RoleBindingList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(RoleBindingToJSON)),
        'pagination': InviteListPaginationToJSON(value.pagination),
    };
}

