/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Assistant Data Plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChoiceChunkModelDelta } from './ChoiceChunkModelDelta';
import {
    ChoiceChunkModelDeltaFromJSON,
    ChoiceChunkModelDeltaFromJSONTyped,
    ChoiceChunkModelDeltaToJSON,
} from './ChoiceChunkModelDelta';

/**
 * Describes a single choice in a chat completion response.
 * @export
 * @interface ChoiceChunkModel
 */
export interface ChoiceChunkModel {
    /**
     * 
     * @type {string}
     * @memberof ChoiceChunkModel
     */
    finishReason?: string;
    /**
     * 
     * @type {number}
     * @memberof ChoiceChunkModel
     */
    index?: number;
    /**
     * 
     * @type {ChoiceChunkModelDelta}
     * @memberof ChoiceChunkModel
     */
    delta?: ChoiceChunkModelDelta;
}

/**
 * Check if a given object implements the ChoiceChunkModel interface.
 */
export function instanceOfChoiceChunkModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChoiceChunkModelFromJSON(json: any): ChoiceChunkModel {
    return ChoiceChunkModelFromJSONTyped(json, false);
}

export function ChoiceChunkModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChoiceChunkModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'finishReason': !exists(json, 'finish_reason') ? undefined : json['finish_reason'],
        'index': !exists(json, 'index') ? undefined : json['index'],
        'delta': !exists(json, 'delta') ? undefined : ChoiceChunkModelDeltaFromJSON(json['delta']),
    };
}

export function ChoiceChunkModelToJSON(value?: ChoiceChunkModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'finish_reason': value.finishReason,
        'index': value.index,
        'delta': ChoiceChunkModelDeltaToJSON(value.delta),
    };
}

