/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Assistant Data Plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2025-01
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MessageModel } from './MessageModel';
import {
    MessageModelFromJSON,
    MessageModelFromJSONTyped,
    MessageModelToJSON,
} from './MessageModel';

/**
 * Parameters to retrieve context from an assistant.
 * @export
 * @interface ContextRequest
 */
export interface ContextRequest {
    /**
     * The query that is used to generate the context. Exactly one of query or messages should be provided.
     * @type {string}
     * @memberof ContextRequest
     */
    query?: string;
    /**
     * Optionally filter which documents can be retrieved using the following metadata fields.
     * @type {object}
     * @memberof ContextRequest
     */
    filter?: object;
    /**
     * The list of messages to use for generating the context. Exactly one of query or messages should be provided.
     * @type {Array<MessageModel>}
     * @memberof ContextRequest
     */
    messages?: Array<MessageModel>;
    /**
     * The number of context snippets to return. Default is 15.
     * @type {number}
     * @memberof ContextRequest
     */
    topK?: number;
}

/**
 * Check if a given object implements the ContextRequest interface.
 */
export function instanceOfContextRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ContextRequestFromJSON(json: any): ContextRequest {
    return ContextRequestFromJSONTyped(json, false);
}

export function ContextRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'query': !exists(json, 'query') ? undefined : json['query'],
        'filter': !exists(json, 'filter') ? undefined : json['filter'],
        'messages': !exists(json, 'messages') ? undefined : ((json['messages'] as Array<any>).map(MessageModelFromJSON)),
        'topK': !exists(json, 'top_k') ? undefined : json['top_k'],
    };
}

export function ContextRequestToJSON(value?: ContextRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'query': value.query,
        'filter': value.filter,
        'messages': value.messages === undefined ? undefined : ((value.messages as Array<any>).map(MessageModelToJSON)),
        'top_k': value.topK,
    };
}

