/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Assistant Data Plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssistantFileModel } from './AssistantFileModel';
import {
    AssistantFileModelFromJSON,
    AssistantFileModelFromJSONTyped,
    AssistantFileModelToJSON,
} from './AssistantFileModel';

/**
 * Represents a reference to a part of a docx document.
 * @export
 * @interface DocxReferenceModel
 */
export interface DocxReferenceModel {
    /**
     * The type of reference. Always "doc_x".
     * @type {string}
     * @memberof DocxReferenceModel
     */
    type: string;
    /**
     * 
     * @type {AssistantFileModel}
     * @memberof DocxReferenceModel
     */
    file: AssistantFileModel;
    /**
     * 
     * @type {Array<number>}
     * @memberof DocxReferenceModel
     */
    pages: Array<number>;
}

/**
 * Check if a given object implements the DocxReferenceModel interface.
 */
export function instanceOfDocxReferenceModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "file" in value;
    isInstance = isInstance && "pages" in value;

    return isInstance;
}

export function DocxReferenceModelFromJSON(json: any): DocxReferenceModel {
    return DocxReferenceModelFromJSONTyped(json, false);
}

export function DocxReferenceModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocxReferenceModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'file': AssistantFileModelFromJSON(json['file']),
        'pages': json['pages'],
    };
}

export function DocxReferenceModelToJSON(value?: DocxReferenceModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'file': AssistantFileModelToJSON(value.file),
        'pages': value.pages,
    };
}

