/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Assistant Data Plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents the data for an image.
 * @export
 * @interface ImageModel
 */
export interface ImageModel {
    /**
     * The format of the image data. Currently, this is always "base64".
     * @type {string}
     * @memberof ImageModel
     */
    type: string;
    /**
     * The MIME type of the image (e.g., "image/jpeg").
     * @type {string}
     * @memberof ImageModel
     */
    mimeType: string;
    /**
     * The image data. Currently, this is always a base64-encoded string.
     * @type {string}
     * @memberof ImageModel
     */
    data: string;
}

/**
 * Check if a given object implements the ImageModel interface.
 */
export function instanceOfImageModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "mimeType" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ImageModelFromJSON(json: any): ImageModel {
    return ImageModelFromJSONTyped(json, false);
}

export function ImageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'mimeType': json['mime_type'],
        'data': json['data'],
    };
}

export function ImageModelToJSON(value?: ImageModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'mime_type': value.mimeType,
        'data': value.data,
    };
}

