/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone assistant data plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2026-04
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentFilterResults } from './ContentFilterResults';
import {
    ContentFilterResultsFromJSON,
    ContentFilterResultsFromJSONTyped,
    ContentFilterResultsToJSON,
} from './ContentFilterResults';
import type { UsageModel } from './UsageModel';
import {
    UsageModelFromJSON,
    UsageModelFromJSONTyped,
    UsageModelToJSON,
} from './UsageModel';

/**
 * The end message in a stream chat response. This chunk signals that the  assistant has finished sending the response and provides the reason  generation stopped along with the token consumption for the interaction.
 * @export
 * @interface MessageEndModel
 */
export interface MessageEndModel {
    /**
     * The type of stream chunk. Always `message_end`.
     * @type {string}
     * @memberof MessageEndModel
     */
    type: string;
    /**
     * A unique identifier for this chat response.
     * @type {string}
     * @memberof MessageEndModel
     */
    id: string;
    /**
     * The name or identifier of the model used to generate this chat response.
     * @type {string}
     * @memberof MessageEndModel
     */
    model: string;
    /**
     * Indicates why the chat response generation stopped. This signals the  end of the stream and no further chunks will be sent for this response.
     * - `stop`: The model finished generating the response.  
     * - `length`: Generation was cut off because the maximum number of tokens allowed was reached.
     * - `content_filter`: Generation stopped because content was blocked by content filtering rules. 
     *   (for example, content that contains hate speech or violent material).
     * 
     * - `tool_calls`: Generation stopped because a tool call was triggered.
     * @type {string}
     * @memberof MessageEndModel
     */
    finishReason: string;
    /**
     * 
     * @type {UsageModel}
     * @memberof MessageEndModel
     */
    usage?: UsageModel;
    /**
     * 
     * @type {ContentFilterResults}
     * @memberof MessageEndModel
     */
    contentFilterResults?: ContentFilterResults;
}

/**
 * Check if a given object implements the MessageEndModel interface.
 */
export function instanceOfMessageEndModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "model" in value;
    isInstance = isInstance && "finishReason" in value;

    return isInstance;
}

export function MessageEndModelFromJSON(json: any): MessageEndModel {
    return MessageEndModelFromJSONTyped(json, false);
}

export function MessageEndModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageEndModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'model': json['model'],
        'finishReason': json['finish_reason'],
        'usage': !exists(json, 'usage') ? undefined : UsageModelFromJSON(json['usage']),
        'contentFilterResults': !exists(json, 'content_filter_results') ? undefined : ContentFilterResultsFromJSON(json['content_filter_results']),
    };
}

export function MessageEndModelToJSON(value?: MessageEndModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'model': value.model,
        'finish_reason': value.finishReason,
        'usage': UsageModelToJSON(value.usage),
        'content_filter_results': ContentFilterResultsToJSON(value.contentFilterResults),
    };
}

