/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Assistant Data Plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MultiModalContentBlocksModel } from './MultiModalContentBlocksModel';
import {
    MultiModalContentBlocksModelFromJSON,
    MultiModalContentBlocksModelFromJSONTyped,
    MultiModalContentBlocksModelToJSON,
} from './MultiModalContentBlocksModel';
import type { TypedReferenceModel } from './TypedReferenceModel';
import {
    TypedReferenceModelFromJSON,
    TypedReferenceModelFromJSONTyped,
    TypedReferenceModelToJSON,
} from './TypedReferenceModel';

/**
 * Represents a multimodal context snippet.
 * @export
 * @interface MultiModalSnippetModel
 */
export interface MultiModalSnippetModel {
    /**
     * The type of context snippet.
     * @type {string}
     * @memberof MultiModalSnippetModel
     */
    type: string;
    /**
     * 
     * @type {Array<MultiModalContentBlocksModel>}
     * @memberof MultiModalSnippetModel
     */
    content: Array<MultiModalContentBlocksModel>;
    /**
     * 
     * @type {number}
     * @memberof MultiModalSnippetModel
     */
    score: number;
    /**
     * 
     * @type {TypedReferenceModel}
     * @memberof MultiModalSnippetModel
     */
    reference: TypedReferenceModel;
}

/**
 * Check if a given object implements the MultiModalSnippetModel interface.
 */
export function instanceOfMultiModalSnippetModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "score" in value;
    isInstance = isInstance && "reference" in value;

    return isInstance;
}

export function MultiModalSnippetModelFromJSON(json: any): MultiModalSnippetModel {
    return MultiModalSnippetModelFromJSONTyped(json, false);
}

export function MultiModalSnippetModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiModalSnippetModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'content': ((json['content'] as Array<any>).map(MultiModalContentBlocksModelFromJSON)),
        'score': json['score'],
        'reference': TypedReferenceModelFromJSON(json['reference']),
    };
}

export function MultiModalSnippetModelToJSON(value?: MultiModalSnippetModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'content': ((value.content as Array<any>).map(MultiModalContentBlocksModelToJSON)),
        'score': value.score,
        'reference': TypedReferenceModelToJSON(value.reference),
    };
}

