/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Assistant Data Plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ImageModel } from './ImageModel';
import {
    ImageModelFromJSON,
    ImageModelFromJSONTyped,
    ImageModelToJSON,
} from './ImageModel';

/**
 * Represents an image block in a multimodal context snippet.
 * @export
 * @interface MultiModalContentImageBlockModel
 */
export interface MultiModalContentImageBlockModel {
    /**
     * The type of multimodal content block.
     * @type {string}
     * @memberof MultiModalContentImageBlockModel
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof MultiModalContentImageBlockModel
     */
    caption: string;
    /**
     * 
     * @type {ImageModel}
     * @memberof MultiModalContentImageBlockModel
     */
    image?: ImageModel | null;
}

/**
 * Check if a given object implements the MultiModalContentImageBlockModel interface.
 */
export function instanceOfMultiModalContentImageBlockModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "caption" in value;

    return isInstance;
}

export function MultiModalContentImageBlockModelFromJSON(json: any): MultiModalContentImageBlockModel {
    return MultiModalContentImageBlockModelFromJSONTyped(json, false);
}

export function MultiModalContentImageBlockModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiModalContentImageBlockModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'caption': json['caption'],
        'image': !exists(json, 'image') ? undefined : ImageModelFromJSON(json['image']),
    };
}

export function MultiModalContentImageBlockModelToJSON(value?: MultiModalContentImageBlockModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'caption': value.caption,
        'image': ImageModelToJSON(value.image),
    };
}

