/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone assistant data plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2026-04
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Object that contains the next pagination token to continue a previous listing operation.
 * @export
 * @interface PaginationResponse
 */
export interface PaginationResponse {
    /**
     * The token to use to retrieve the next page of results.
     * @type {string}
     * @memberof PaginationResponse
     */
    next: string;
}

/**
 * Check if a given object implements the PaginationResponse interface.
 */
export function instanceOfPaginationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "next" in value;

    return isInstance;
}

export function PaginationResponseFromJSON(json: any): PaginationResponse {
    return PaginationResponseFromJSONTyped(json, false);
}

export function PaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'next': json['next'],
    };
}

export function PaginationResponseToJSON(value?: PaginationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'next': value.next,
    };
}

