/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone assistant data plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2026-04
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChoiceChunkModel } from './ChoiceChunkModel';
import {
    ChoiceChunkModelFromJSON,
    ChoiceChunkModelFromJSONTyped,
    ChoiceChunkModelToJSON,
} from './ChoiceChunkModel';

/**
 * Describes the response format of a chat request.
 * @export
 * @interface StreamChatCompletionChunkModel
 */
export interface StreamChatCompletionChunkModel {
    /**
     * A unique identifier for this chat response.
     * @type {string}
     * @memberof StreamChatCompletionChunkModel
     */
    id?: string;
    /**
     * A list of chat completion choices.
     * @type {Array<ChoiceChunkModel>}
     * @memberof StreamChatCompletionChunkModel
     */
    choices?: Array<ChoiceChunkModel>;
    /**
     * The name or identifier of the model used to generate this chat response.
     * @type {string}
     * @memberof StreamChatCompletionChunkModel
     */
    model?: string;
}

/**
 * Check if a given object implements the StreamChatCompletionChunkModel interface.
 */
export function instanceOfStreamChatCompletionChunkModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StreamChatCompletionChunkModelFromJSON(json: any): StreamChatCompletionChunkModel {
    return StreamChatCompletionChunkModelFromJSONTyped(json, false);
}

export function StreamChatCompletionChunkModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamChatCompletionChunkModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'choices': !exists(json, 'choices') ? undefined : ((json['choices'] as Array<any>).map(ChoiceChunkModelFromJSON)),
        'model': !exists(json, 'model') ? undefined : json['model'],
    };
}

export function StreamChatCompletionChunkModelToJSON(value?: StreamChatCompletionChunkModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'choices': value.choices === undefined ? undefined : ((value.choices as Array<any>).map(ChoiceChunkModelToJSON)),
        'model': value.model,
    };
}

