/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Assistant Data Plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TypedReferenceModel } from './TypedReferenceModel';
import {
    TypedReferenceModelFromJSON,
    TypedReferenceModelFromJSONTyped,
    TypedReferenceModelToJSON,
} from './TypedReferenceModel';

/**
 * Represents a text context snippet.
 * @export
 * @interface TextSnippetModel
 */
export interface TextSnippetModel {
    /**
     * The type of context snippet.
     * @type {string}
     * @memberof TextSnippetModel
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof TextSnippetModel
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof TextSnippetModel
     */
    score: number;
    /**
     * 
     * @type {TypedReferenceModel}
     * @memberof TextSnippetModel
     */
    reference: TypedReferenceModel;
}

/**
 * Check if a given object implements the TextSnippetModel interface.
 */
export function instanceOfTextSnippetModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "score" in value;
    isInstance = isInstance && "reference" in value;

    return isInstance;
}

export function TextSnippetModelFromJSON(json: any): TextSnippetModel {
    return TextSnippetModelFromJSONTyped(json, false);
}

export function TextSnippetModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextSnippetModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'content': json['content'],
        'score': json['score'],
        'reference': TypedReferenceModelFromJSON(json['reference']),
    };
}

export function TextSnippetModelToJSON(value?: TextSnippetModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'content': value.content,
        'score': value.score,
        'reference': TypedReferenceModelToJSON(value.reference),
    };
}

