/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Assistant Data Plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DocxReferenceModel,
    instanceOfDocxReferenceModel,
    DocxReferenceModelFromJSON,
    DocxReferenceModelFromJSONTyped,
    DocxReferenceModelToJSON,
} from './DocxReferenceModel';
import {
    JsonReferenceModel,
    instanceOfJsonReferenceModel,
    JsonReferenceModelFromJSON,
    JsonReferenceModelFromJSONTyped,
    JsonReferenceModelToJSON,
} from './JsonReferenceModel';
import {
    MarkdownReferenceModel,
    instanceOfMarkdownReferenceModel,
    MarkdownReferenceModelFromJSON,
    MarkdownReferenceModelFromJSONTyped,
    MarkdownReferenceModelToJSON,
} from './MarkdownReferenceModel';
import {
    PdfReferenceModel,
    instanceOfPdfReferenceModel,
    PdfReferenceModelFromJSON,
    PdfReferenceModelFromJSONTyped,
    PdfReferenceModelToJSON,
} from './PdfReferenceModel';
import {
    TextReferenceModel,
    instanceOfTextReferenceModel,
    TextReferenceModelFromJSON,
    TextReferenceModelFromJSONTyped,
    TextReferenceModelToJSON,
} from './TextReferenceModel';

/**
 * @type TypedReferenceModel
 * Represents a reference for the information provided.
 * @export
 */
export type TypedReferenceModel = { type: 'doc_x' } & DocxReferenceModel | { type: 'json' } & JsonReferenceModel | { type: 'markdown' } & MarkdownReferenceModel | { type: 'pdf' } & PdfReferenceModel | { type: 'text' } & TextReferenceModel;

export function TypedReferenceModelFromJSON(json: any): TypedReferenceModel {
    return TypedReferenceModelFromJSONTyped(json, false);
}

export function TypedReferenceModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedReferenceModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'doc_x':
            return {...DocxReferenceModelFromJSONTyped(json, true), type: 'doc_x'};
        case 'json':
            return {...JsonReferenceModelFromJSONTyped(json, true), type: 'json'};
        case 'markdown':
            return {...MarkdownReferenceModelFromJSONTyped(json, true), type: 'markdown'};
        case 'pdf':
            return {...PdfReferenceModelFromJSONTyped(json, true), type: 'pdf'};
        case 'text':
            return {...TextReferenceModelFromJSONTyped(json, true), type: 'text'};
        default:
            throw new Error(`No variant of TypedReferenceModel exists with 'type=${json['type']}'`);
    }
}

export function TypedReferenceModelToJSON(value?: TypedReferenceModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'doc_x':
            return DocxReferenceModelToJSON(value);
        case 'json':
            return JsonReferenceModelToJSON(value);
        case 'markdown':
            return MarkdownReferenceModelToJSON(value);
        case 'pdf':
            return PdfReferenceModelToJSON(value);
        case 'text':
            return TextReferenceModelToJSON(value);
        default:
            throw new Error(`No variant of TypedReferenceModel exists with 'type=${value['type']}'`);
    }

}

