/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone assistant data plane API
 * Pinecone Assistant Engine is a context engine to store and retrieve relevant knowledge from millions of documents at scale. This API supports interactions with assistants.
 *
 * The version of the OpenAPI document: 2026-04
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Describes the token usage associated with interactions with an assistant.
 * @export
 * @interface UsageModel
 */
export interface UsageModel {
    /**
     * For chat interactions, the number of tokens in the LLM request (message, context snippets, and system prompt).
     * For context retrieval, the number of tokens in the LLM request used to generate search queries from the messages, plus the tokens in the retrieved context snippets.
     * @type {number}
     * @memberof UsageModel
     */
    promptTokens?: number;
    /**
     * For chat interactions, the number of tokens in the assistant's response.  
     * For context retrieval, this is always 0.
     * @type {number}
     * @memberof UsageModel
     */
    completionTokens?: number;
    /**
     * The total number of tokens used, equal to the sum of `prompt_tokens` and `completion_tokens`.
     * @type {number}
     * @memberof UsageModel
     */
    totalTokens?: number;
}

/**
 * Check if a given object implements the UsageModel interface.
 */
export function instanceOfUsageModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsageModelFromJSON(json: any): UsageModel {
    return UsageModelFromJSONTyped(json, false);
}

export function UsageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'promptTokens': !exists(json, 'prompt_tokens') ? undefined : json['prompt_tokens'],
        'completionTokens': !exists(json, 'completion_tokens') ? undefined : json['completion_tokens'],
        'totalTokens': !exists(json, 'total_tokens') ? undefined : json['total_tokens'],
    };
}

export function UsageModelToJSON(value?: UsageModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prompt_tokens': value.promptTokens,
        'completion_tokens': value.completionTokens,
        'total_tokens': value.totalTokens,
    };
}

