name: 'Test legacy index on GCPS'
description: 'Uses new client to interact with index created via legacy client'

inputs:
  pinecone_client_version:
    description: 'The version of the Pinecone client to use'
    required: false
    default: 'spruceDev'
  index_name:
    description: 'The name of the index'
    required: true
  PINECONE_ENVIRONMENT:
    description: 'The environment of the index'
    required: true
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  records_to_upsert:
    description: 'The number of records to upsert'
    required: false
    default: '1000'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://registry.npmjs.org'
    - name: Install pinecone, compile, and run create index script
      shell: bash
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        INDEX_NAME: ${{ inputs.index_name }}
      run: |
        set -x
        cd ..
        cp -r pinecone-ts-client/ts-migration-tests/2.x/test-and-delete-all-indexes test-and-delete-all-indexes
        cd test-and-delete-all-indexes
        npm install typescript@latest --no-cache
        npm install @pinecone-database/pinecone@${{ inputs.pinecone_client_version }} --no-cache
        cat package.json
        cat package-lock.json
        npm run build
        npm run testIndex
