name: 'Version Bump'
description: 'Unified version bumping for prod, RC, and dev releases'
inputs:
  releaseMode:
    description: 'Release mode (prod, rc, dev)'
    required: true
  releaseType:
    description: 'Semver release type for prod releases (major, minor, patch)'
    required: false
    default: 'patch'
  rc_name:
    description: 'RC identifier for RC releases (e.g., "2024-07")'
    required: false
    default: ''
outputs:
  version:
    description: 'The new version string'
    value: ${{ steps.version-bump.outputs.version }}
  version_file:
    description: 'Path to the version.json file (for dev releases)'
    value: ${{ steps.version-bump.outputs.version_file }}
runs:
  using: 'composite'
  steps:
    - name: 'Bump version for production release'
      if: inputs.releaseMode == 'prod'
      shell: bash
      id: version-bump
      run: |
        npm version ${{ inputs.releaseType }} --no-git-tag-version
        newVersion=$(jq -r '.version' package.json)
        echo "version=$newVersion" >> $GITHUB_OUTPUT
        echo "Bumped version to $newVersion (prod release)"

    - name: 'Bump version for RC release'
      if: inputs.releaseMode == 'rc'
      shell: bash
      id: version-bump
      run: |
        if [ -z "${{ inputs.rc_name }}" ]; then
          echo "Error: rc_name is required for RC releases"
          exit 1
        fi
        npm version prerelease --preid=rc.${{ inputs.rc_name }} --no-git-tag-version
        newVersion=$(jq -r '.version' package.json)
        echo "version=$newVersion" >> $GITHUB_OUTPUT
        echo "Bumped version to $newVersion (RC release)"

    - name: 'Bump version for dev release'
      if: inputs.releaseMode == 'dev'
      shell: bash
      id: version-bump
      run: |
        currentVersion=$(jq -r '.version' package.json)
        timestamp=$(date +%Y%m%d%H%M%S)
        devVersion="$currentVersion-dev.$timestamp"
        
        # Update package.json
        jq --arg newVersion "$devVersion" '.version = $newVersion' package.json > package.tmp && mv package.tmp package.json
        
        # Update package-lock.json version
        jq --arg newVersion "$devVersion" '.version = $newVersion' package-lock.json > package-lock.tmp && mv package-lock.tmp package-lock.json
        
        # Update package-lock.json packages[""].version
        jq --arg newVersion "$devVersion" '.packages[""].version = $newVersion' package-lock.json > package-lock.tmp && mv package-lock.tmp package-lock.json
        
        # Create version.json file
        versionFile="src/version.json"
        jq --null-input --arg version "$devVersion" '{"name": "@pinecone-database/pinecone", "version": $version}' > "$versionFile"
        
        echo "version=$devVersion" >> $GITHUB_OUTPUT
        echo "version_file=$versionFile" >> $GITHUB_OUTPUT
        echo "Bumped version to $devVersion (dev release)"
