/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-01.alpha
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SparseValues } from './SparseValues';
import {
    SparseValuesFromJSON,
    SparseValuesFromJSONTyped,
    SparseValuesToJSON,
} from './SparseValues';

/**
 * A scoring method that defines how documents are scored against a query.
 * 
 * The `type` field determines which other fields are used:
 * - `dense_vector`: Score by dense vector similarity. Requires `field` or `fields`, and a `values` array.
 * - `sparse_vector`: Score by sparse vector similarity. Requires `field` or `fields`, and `sparse_values`.
 * - `text`: Score by BM25 text similarity against a single field. Requires `field` or `fields`, and `query`.
 * - `query_string`: Score using a Lucene query string. Use field qualifiers (`field:(clause)`) to target a field, or omit field qualifiers to search against all text-searchable fields. Errors if `field` or `fields` is provided.
 * @export
 * @interface DocumentScoringMethod
 */
export interface DocumentScoringMethod {
    /**
     * The scoring method type.
     * Possible values: `dense_vector`, `sparse_vector`, `text`, or `query_string`.
     * @type {string}
     * @memberof DocumentScoringMethod
     */
    type: string;
    /**
     * The field to score against.
     * 
     * Required for `dense_vector`, `sparse_vector`, and `text` scoring types. Must not be provided for `query_string`.
     * @type {string}
     * @memberof DocumentScoringMethod
     */
    field?: string;
    /**
     * The text query to use for `text` and `query_string` scoring types.
     * @type {string}
     * @memberof DocumentScoringMethod
     */
    query?: string;
    /**
     * The dense vector values to use for `dense_vector` scoring type.
     * @type {Array<number>}
     * @memberof DocumentScoringMethod
     */
    values?: Array<number>;
    /**
     * 
     * @type {SparseValues}
     * @memberof DocumentScoringMethod
     */
    sparseValues?: SparseValues;
}

/**
 * Check if a given object implements the DocumentScoringMethod interface.
 */
export function instanceOfDocumentScoringMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function DocumentScoringMethodFromJSON(json: any): DocumentScoringMethod {
    return DocumentScoringMethodFromJSONTyped(json, false);
}

export function DocumentScoringMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentScoringMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'field': !exists(json, 'field') ? undefined : json['field'],
        'query': !exists(json, 'query') ? undefined : json['query'],
        'values': !exists(json, 'values') ? undefined : json['values'],
        'sparseValues': !exists(json, 'sparse_values') ? undefined : SparseValuesFromJSON(json['sparse_values']),
    };
}

export function DocumentScoringMethodToJSON(value?: DocumentScoringMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'field': value.field,
        'query': value.query,
        'values': value.values,
        'sparse_values': SparseValuesToJSON(value.sparseValues),
    };
}

