/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-01.alpha
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentScoringMethod } from './DocumentScoringMethod';
import {
    DocumentScoringMethodFromJSON,
    DocumentScoringMethodFromJSONTyped,
    DocumentScoringMethodToJSON,
} from './DocumentScoringMethod';

/**
 * The request for the `search_documents` operation.
 * @export
 * @interface SearchDocumentsRequest
 */
export interface SearchDocumentsRequest {
    /**
     * The list of scoring methods to use for ranking documents.
     * @type {Array<DocumentScoringMethod>}
     * @memberof SearchDocumentsRequest
     */
    scoreBy: Array<DocumentScoringMethod>;
    /**
     * The number of top-ranked documents to return.
     * @type {number}
     * @memberof SearchDocumentsRequest
     */
    topK: number;
    /**
     * The document fields to include in the search results.
     * @type {Array<string>}
     * @memberof SearchDocumentsRequest
     */
    includeFields?: Array<string>;
    /**
     * A metadata filter expression to restrict the documents searched.
     * @type {object}
     * @memberof SearchDocumentsRequest
     */
    filter?: object;
}

/**
 * Check if a given object implements the SearchDocumentsRequest interface.
 */
export function instanceOfSearchDocumentsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "scoreBy" in value;
    isInstance = isInstance && "topK" in value;

    return isInstance;
}

export function SearchDocumentsRequestFromJSON(json: any): SearchDocumentsRequest {
    return SearchDocumentsRequestFromJSONTyped(json, false);
}

export function SearchDocumentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDocumentsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scoreBy': ((json['score_by'] as Array<any>).map(DocumentScoringMethodFromJSON)),
        'topK': json['top_k'],
        'includeFields': !exists(json, 'include_fields') ? undefined : json['include_fields'],
        'filter': !exists(json, 'filter') ? undefined : json['filter'],
    };
}

export function SearchDocumentsRequestToJSON(value?: SearchDocumentsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'score_by': ((value.scoreBy as Array<any>).map(DocumentScoringMethodToJSON)),
        'top_k': value.topK,
        'include_fields': value.includeFields,
        'filter': value.filter,
    };
}

