/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-01.alpha
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The response for the `upsert_documents` operation.
 * @export
 * @interface UpsertDocumentsResponse
 */
export interface UpsertDocumentsResponse {
    /**
     * The number of documents successfully upserted.
     * @type {number}
     * @memberof UpsertDocumentsResponse
     */
    upsertedCount: number;
}

/**
 * Check if a given object implements the UpsertDocumentsResponse interface.
 */
export function instanceOfUpsertDocumentsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "upsertedCount" in value;

    return isInstance;
}

export function UpsertDocumentsResponseFromJSON(json: any): UpsertDocumentsResponse {
    return UpsertDocumentsResponseFromJSONTyped(json, false);
}

export function UpsertDocumentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertDocumentsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'upsertedCount': json['upserted_count'],
    };
}

export function UpsertDocumentsResponseToJSON(value?: UpsertDocumentsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'upserted_count': value.upsertedCount,
    };
}

