/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNamespaceRequestSchemaFieldsValue
 */
export interface CreateNamespaceRequestSchemaFieldsValue {
    /**
     * Whether the field is filterable. If true, the field is indexed and can be used in filters. Only true values are allowed.
     * @type {boolean}
     * @memberof CreateNamespaceRequestSchemaFieldsValue
     */
    filterable?: boolean;
}

/**
 * Check if a given object implements the CreateNamespaceRequestSchemaFieldsValue interface.
 */
export function instanceOfCreateNamespaceRequestSchemaFieldsValue(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateNamespaceRequestSchemaFieldsValueFromJSON(json: any): CreateNamespaceRequestSchemaFieldsValue {
    return CreateNamespaceRequestSchemaFieldsValueFromJSONTyped(json, false);
}

export function CreateNamespaceRequestSchemaFieldsValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNamespaceRequestSchemaFieldsValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filterable': !exists(json, 'filterable') ? undefined : json['filterable'],
    };
}

export function CreateNamespaceRequestSchemaFieldsValueToJSON(value?: CreateNamespaceRequestSchemaFieldsValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filterable': value.filterable,
    };
}

