/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateNamespaceRequestSchema } from './CreateNamespaceRequestSchema';
import {
    CreateNamespaceRequestSchemaFromJSON,
    CreateNamespaceRequestSchemaFromJSONTyped,
    CreateNamespaceRequestSchemaToJSON,
} from './CreateNamespaceRequestSchema';

/**
 * A request for creating a namespace with the specified namespace name.
 * @export
 * @interface CreateNamespaceRequest
 */
export interface CreateNamespaceRequest {
    /**
     * The name of the namespace.
     * @type {string}
     * @memberof CreateNamespaceRequest
     */
    name: string;
    /**
     * 
     * @type {CreateNamespaceRequestSchema}
     * @memberof CreateNamespaceRequest
     */
    schema?: CreateNamespaceRequestSchema;
}

/**
 * Check if a given object implements the CreateNamespaceRequest interface.
 */
export function instanceOfCreateNamespaceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateNamespaceRequestFromJSON(json: any): CreateNamespaceRequest {
    return CreateNamespaceRequestFromJSONTyped(json, false);
}

export function CreateNamespaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNamespaceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'schema': !exists(json, 'schema') ? undefined : CreateNamespaceRequestSchemaFromJSON(json['schema']),
    };
}

export function CreateNamespaceRequestToJSON(value?: CreateNamespaceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'schema': CreateNamespaceRequestSchemaToJSON(value.schema),
    };
}

