/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';
import type { Usage } from './Usage';
import {
    UsageFromJSON,
    UsageFromJSONTyped,
    UsageToJSON,
} from './Usage';
import type { Vector } from './Vector';
import {
    VectorFromJSON,
    VectorFromJSONTyped,
    VectorToJSON,
} from './Vector';

/**
 * The response for the `fetch_by_metadata` operation.
 * @export
 * @interface FetchByMetadataResponse
 */
export interface FetchByMetadataResponse {
    /**
     * The fetched vectors, in the form of a map between the fetched ids and the fetched vectors
     * @type {{ [key: string]: Vector; }}
     * @memberof FetchByMetadataResponse
     */
    vectors?: { [key: string]: Vector; };
    /**
     * The namespace of the vectors.
     * @type {string}
     * @memberof FetchByMetadataResponse
     */
    namespace?: string;
    /**
     * 
     * @type {Usage}
     * @memberof FetchByMetadataResponse
     */
    usage?: Usage;
    /**
     * 
     * @type {Pagination}
     * @memberof FetchByMetadataResponse
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the FetchByMetadataResponse interface.
 */
export function instanceOfFetchByMetadataResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FetchByMetadataResponseFromJSON(json: any): FetchByMetadataResponse {
    return FetchByMetadataResponseFromJSONTyped(json, false);
}

export function FetchByMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchByMetadataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vectors': !exists(json, 'vectors') ? undefined : (mapValues(json['vectors'], VectorFromJSON)),
        'namespace': !exists(json, 'namespace') ? undefined : json['namespace'],
        'usage': !exists(json, 'usage') ? undefined : UsageFromJSON(json['usage']),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function FetchByMetadataResponseToJSON(value?: FetchByMetadataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vectors': value.vectors === undefined ? undefined : (mapValues(value.vectors, VectorToJSON)),
        'namespace': value.namespace,
        'usage': UsageToJSON(value.usage),
        'pagination': PaginationToJSON(value.pagination),
    };
}

