/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-07
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The value of a single metadata field. Nested objects and mixed-type lists are rejected: "Metadata value must be a string, number, boolean or list of strings".
 * @export
 * @interface MetadataValue
 */
export interface MetadataValue {
}

/**
 * Check if a given object implements the MetadataValue interface.
 */
export function instanceOfMetadataValue(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MetadataValueFromJSON(json: any): MetadataValue {
    return MetadataValueFromJSONTyped(json, false);
}

export function MetadataValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataValue {
    return json;
}

export function MetadataValueToJSON(value?: MetadataValue | null): any {
    return value;
}

