/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateNamespaceRequestSchema } from './CreateNamespaceRequestSchema';
import {
    CreateNamespaceRequestSchemaFromJSON,
    CreateNamespaceRequestSchemaFromJSONTyped,
    CreateNamespaceRequestSchemaToJSON,
} from './CreateNamespaceRequestSchema';
import type { NamespaceDescriptionIndexedFields } from './NamespaceDescriptionIndexedFields';
import {
    NamespaceDescriptionIndexedFieldsFromJSON,
    NamespaceDescriptionIndexedFieldsFromJSONTyped,
    NamespaceDescriptionIndexedFieldsToJSON,
} from './NamespaceDescriptionIndexedFields';

/**
 * A description of a namespace, including the name and record count.
 * @export
 * @interface NamespaceDescription
 */
export interface NamespaceDescription {
    /**
     * The name of the namespace.
     * @type {string}
     * @memberof NamespaceDescription
     */
    name?: string;
    /**
     * The total amount of records within the namespace.
     * @type {number}
     * @memberof NamespaceDescription
     */
    recordCount?: number;
    /**
     * 
     * @type {CreateNamespaceRequestSchema}
     * @memberof NamespaceDescription
     */
    schema?: CreateNamespaceRequestSchema;
    /**
     * 
     * @type {NamespaceDescriptionIndexedFields}
     * @memberof NamespaceDescription
     */
    indexedFields?: NamespaceDescriptionIndexedFields;
}

/**
 * Check if a given object implements the NamespaceDescription interface.
 */
export function instanceOfNamespaceDescription(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NamespaceDescriptionFromJSON(json: any): NamespaceDescription {
    return NamespaceDescriptionFromJSONTyped(json, false);
}

export function NamespaceDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamespaceDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'recordCount': !exists(json, 'record_count') ? undefined : json['record_count'],
        'schema': !exists(json, 'schema') ? undefined : CreateNamespaceRequestSchemaFromJSON(json['schema']),
        'indexedFields': !exists(json, 'indexed_fields') ? undefined : NamespaceDescriptionIndexedFieldsFromJSON(json['indexed_fields']),
    };
}

export function NamespaceDescriptionToJSON(value?: NamespaceDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'record_count': value.recordCount,
        'schema': CreateNamespaceRequestSchemaToJSON(value.schema),
        'indexed_fields': NamespaceDescriptionIndexedFieldsToJSON(value.indexedFields),
    };
}

