/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-01
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The query inputs to search with.
 * @export
 * @interface SearchRecordsRequestQuery
 */
export interface SearchRecordsRequestQuery {
    /**
     * The number of results to return for each search.
     * @type {number}
     * @memberof SearchRecordsRequestQuery
     */
    topK: number;
    /**
     * The filter to apply.
     * @type {object}
     * @memberof SearchRecordsRequestQuery
     */
    filter?: object;
    /**
     * 
     * @type {object}
     * @memberof SearchRecordsRequestQuery
     */
    inputs?: object;
    /**
     * This is the vector data included in the request.
     * @type {Array<number>}
     * @memberof SearchRecordsRequestQuery
     */
    vector?: Array<number>;
}

/**
 * Check if a given object implements the SearchRecordsRequestQuery interface.
 */
export function instanceOfSearchRecordsRequestQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "topK" in value;

    return isInstance;
}

export function SearchRecordsRequestQueryFromJSON(json: any): SearchRecordsRequestQuery {
    return SearchRecordsRequestQueryFromJSONTyped(json, false);
}

export function SearchRecordsRequestQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRecordsRequestQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topK': json['top_k'],
        'filter': !exists(json, 'filter') ? undefined : json['filter'],
        'inputs': !exists(json, 'inputs') ? undefined : json['inputs'],
        'vector': !exists(json, 'vector') ? undefined : json['vector'],
    };
}

export function SearchRecordsRequestQueryToJSON(value?: SearchRecordsRequestQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'top_k': value.topK,
        'filter': value.filter,
        'inputs': value.inputs,
        'vector': value.vector,
    };
}

