/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The response for the `update` operation.
 * @export
 * @interface UpdateResponse
 */
export interface UpdateResponse {
    /**
     * The number of records that matched the filter (if a filter was provided).
     * @type {number}
     * @memberof UpdateResponse
     */
    matchedRecords?: number;
}

/**
 * Check if a given object implements the UpdateResponse interface.
 */
export function instanceOfUpdateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateResponseFromJSON(json: any): UpdateResponse {
    return UpdateResponseFromJSONTyped(json, false);
}

export function UpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'matchedRecords': !exists(json, 'matchedRecords') ? undefined : json['matchedRecords'],
    };
}

export function UpdateResponseToJSON(value?: UpdateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'matchedRecords': value.matchedRecords,
    };
}

