/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-07
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The response for the `update_documents` operation.
 * @export
 * @interface UpdateDocumentsResponse
 */
export interface UpdateDocumentsResponse {
    /**
     * The number of documents that matched `filter` when the update was accepted. Only returned for a filtered update; a per-ID update reports no count. The patch is applied asynchronously, so this is a point-in-time count rather than a guarantee of the number of documents ultimately patched.
     * @type {number}
     * @memberof UpdateDocumentsResponse
     */
    matchedRecords?: number;
}

/**
 * Check if a given object implements the UpdateDocumentsResponse interface.
 */
export function instanceOfUpdateDocumentsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateDocumentsResponseFromJSON(json: any): UpdateDocumentsResponse {
    return UpdateDocumentsResponseFromJSONTyped(json, false);
}

export function UpdateDocumentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDocumentsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'matchedRecords': !exists(json, 'matched_records') ? undefined : json['matched_records'],
    };
}

export function UpdateDocumentsResponseToJSON(value?: UpdateDocumentsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'matched_records': value.matchedRecords,
    };
}

