/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Data Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: unstable
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Any embedding parameters or field mappings to include with the record.
 * @export
 * @interface UpsertRecordEmbed
 */
export interface UpsertRecordEmbed {
    /**
     * Identifies the name of the text field from your document model that will be embedded.
     * @type {object}
     * @memberof UpsertRecordEmbed
     */
    inputs?: object;
}

/**
 * Check if a given object implements the UpsertRecordEmbed interface.
 */
export function instanceOfUpsertRecordEmbed(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpsertRecordEmbedFromJSON(json: any): UpsertRecordEmbed {
    return UpsertRecordEmbedFromJSONTyped(json, false);
}

export function UpsertRecordEmbedFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertRecordEmbed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inputs': !exists(json, 'inputs') ? undefined : json['inputs'],
    };
}

export function UpsertRecordEmbedToJSON(value?: UpsertRecordEmbed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inputs': value.inputs,
    };
}

