/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-07
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IndexSchemaField } from './IndexSchemaField';
import {
    IndexSchemaFieldFromJSON,
    IndexSchemaFieldFromJSONTyped,
    IndexSchemaFieldToJSON,
} from './IndexSchemaField';

/**
 * Index schema associated with the backup, or `null` if not applicable.
 * @export
 * @interface BackupScheduleHistoryItemSchema
 */
export interface BackupScheduleHistoryItemSchema {
    /**
     * A map of field names to their configurations. Field names must be unique, non-empty strings and must not use the reserved names `_id`, `_values`, or `_sparse_values`.
     * @type {{ [key: string]: IndexSchemaField; }}
     * @memberof BackupScheduleHistoryItemSchema
     */
    fields: { [key: string]: IndexSchemaField; };
}

/**
 * Check if a given object implements the BackupScheduleHistoryItemSchema interface.
 */
export function instanceOfBackupScheduleHistoryItemSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fields" in value;

    return isInstance;
}

export function BackupScheduleHistoryItemSchemaFromJSON(json: any): BackupScheduleHistoryItemSchema {
    return BackupScheduleHistoryItemSchemaFromJSONTyped(json, false);
}

export function BackupScheduleHistoryItemSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupScheduleHistoryItemSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fields': (mapValues(json['fields'], IndexSchemaFieldFromJSON)),
    };
}

export function BackupScheduleHistoryItemSchemaToJSON(value?: BackupScheduleHistoryItemSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fields': (mapValues(value.fields, IndexSchemaFieldToJSON)),
    };
}

