/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-07
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BackupScheduleHistoryItemSchema } from './BackupScheduleHistoryItemSchema';
import {
    BackupScheduleHistoryItemSchemaFromJSON,
    BackupScheduleHistoryItemSchemaFromJSONTyped,
    BackupScheduleHistoryItemSchemaToJSON,
} from './BackupScheduleHistoryItemSchema';

/**
 * A backup produced by a schedule, including lifecycle status. When `status` is `Scheduled`, `scheduled_execution_at` is set to the planned run time.
 * @export
 * @interface BackupScheduleHistoryItem
 */
export interface BackupScheduleHistoryItem {
    /**
     * Unique identifier for the backup.
     * @type {string}
     * @memberof BackupScheduleHistoryItem
     */
    backupId: string;
    /**
     * ID of the index from which the backup was taken.
     * @type {string}
     * @memberof BackupScheduleHistoryItem
     */
    sourceIndexId: string;
    /**
     * Name of the index from which the backup was taken.
     * @type {string}
     * @memberof BackupScheduleHistoryItem
     */
    sourceIndexName: string;
    /**
     * Custom user tags on this backup snapshot. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '_', or '-'. Values must be alphanumeric, ';', '@', '_', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string. `null` when no tags are set.
     * @type {{ [key: string]: string; }}
     * @memberof BackupScheduleHistoryItem
     */
    tags?: { [key: string]: string; } | null;
    /**
     * Name of the backup.
     * @type {string}
     * @memberof BackupScheduleHistoryItem
     */
    name: string;
    /**
     * Optional description of the backup, or `null`.
     * @type {string}
     * @memberof BackupScheduleHistoryItem
     */
    description?: string | null;
    /**
     * Current lifecycle status of the backup.
     * @type {string}
     * @memberof BackupScheduleHistoryItem
     */
    status: string;
    /**
     * Cloud provider where the backup is stored.
     * @type {string}
     * @memberof BackupScheduleHistoryItem
     */
    cloud: string;
    /**
     * Cloud region where the backup is stored.
     * @type {string}
     * @memberof BackupScheduleHistoryItem
     */
    region: string;
    /**
     * 
     * @type {BackupScheduleHistoryItemSchema}
     * @memberof BackupScheduleHistoryItem
     */
    schema?: BackupScheduleHistoryItemSchema | null;
    /**
     * Total number of records in the backup.
     * @type {number}
     * @memberof BackupScheduleHistoryItem
     */
    recordCount: number;
    /**
     * Number of namespaces in the backup.
     * @type {number}
     * @memberof BackupScheduleHistoryItem
     */
    namespaceCount: number;
    /**
     * Approximate stored size of this scheduled-backup snapshot, in bytes.
     * @type {number}
     * @memberof BackupScheduleHistoryItem
     */
    sizeBytes: number;
    /**
     * RFC 3339 timestamp when the backup record was created.
     * @type {Date}
     * @memberof BackupScheduleHistoryItem
     */
    createdAt: Date;
    /**
     * Present when `status` is `Scheduled`. RFC 3339 timestamp when the backup is planned to run.
     * @type {Date}
     * @memberof BackupScheduleHistoryItem
     */
    scheduledExecutionAt?: Date;
}

/**
 * Check if a given object implements the BackupScheduleHistoryItem interface.
 */
export function instanceOfBackupScheduleHistoryItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "backupId" in value;
    isInstance = isInstance && "sourceIndexId" in value;
    isInstance = isInstance && "sourceIndexName" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "cloud" in value;
    isInstance = isInstance && "region" in value;
    isInstance = isInstance && "recordCount" in value;
    isInstance = isInstance && "namespaceCount" in value;
    isInstance = isInstance && "sizeBytes" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function BackupScheduleHistoryItemFromJSON(json: any): BackupScheduleHistoryItem {
    return BackupScheduleHistoryItemFromJSONTyped(json, false);
}

export function BackupScheduleHistoryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupScheduleHistoryItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'backupId': json['backup_id'],
        'sourceIndexId': json['source_index_id'],
        'sourceIndexName': json['source_index_name'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'status': json['status'],
        'cloud': json['cloud'],
        'region': json['region'],
        'schema': !exists(json, 'schema') ? undefined : BackupScheduleHistoryItemSchemaFromJSON(json['schema']),
        'recordCount': json['record_count'],
        'namespaceCount': json['namespace_count'],
        'sizeBytes': json['size_bytes'],
        'createdAt': (new Date(json['created_at'])),
        'scheduledExecutionAt': !exists(json, 'scheduled_execution_at') ? undefined : (new Date(json['scheduled_execution_at'])),
    };
}

export function BackupScheduleHistoryItemToJSON(value?: BackupScheduleHistoryItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'backup_id': value.backupId,
        'source_index_id': value.sourceIndexId,
        'source_index_name': value.sourceIndexName,
        'tags': value.tags,
        'name': value.name,
        'description': value.description,
        'status': value.status,
        'cloud': value.cloud,
        'region': value.region,
        'schema': BackupScheduleHistoryItemSchemaToJSON(value.schema),
        'record_count': value.recordCount,
        'namespace_count': value.namespaceCount,
        'size_bytes': value.sizeBytes,
        'created_at': (value.createdAt.toISOString()),
        'scheduled_execution_at': value.scheduledExecutionAt === undefined ? undefined : (value.scheduledExecutionAt.toISOString()),
    };
}

