/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadCapacity } from './ReadCapacity';
import {
    ReadCapacityFromJSON,
    ReadCapacityFromJSONTyped,
    ReadCapacityToJSON,
} from './ReadCapacity';

/**
 * Updated configuration for a BYOC index
 * @export
 * @interface BYOC1Byoc
 */
export interface BYOC1Byoc {
    /**
     * 
     * @type {ReadCapacity}
     * @memberof BYOC1Byoc
     */
    readCapacity?: ReadCapacity;
}

/**
 * Check if a given object implements the BYOC1Byoc interface.
 */
export function instanceOfBYOC1Byoc(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BYOC1ByocFromJSON(json: any): BYOC1Byoc {
    return BYOC1ByocFromJSONTyped(json, false);
}

export function BYOC1ByocFromJSONTyped(json: any, ignoreDiscriminator: boolean): BYOC1Byoc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'readCapacity': !exists(json, 'read_capacity') ? undefined : ReadCapacityFromJSON(json['read_capacity']),
    };
}

export function BYOC1ByocToJSON(value?: BYOC1Byoc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'read_capacity': ReadCapacityToJSON(value.readCapacity),
    };
}

