/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-07
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IndexSchemaField } from './IndexSchemaField';
import {
    IndexSchemaFieldFromJSON,
    IndexSchemaFieldFromJSONTyped,
    IndexSchemaFieldToJSON,
} from './IndexSchemaField';

/**
 * The schema of a Pinecone index. The schema defines the typed fields that documents in the index can contain, including vector fields, semantic text fields, and metadata fields.
 * @export
 * @interface IndexSchema
 */
export interface IndexSchema {
    /**
     * A map of field names to their configurations.
     * Indexes that are served by the vectors API — created with the reserved `_values` / `_sparse_values` schema, or created by an earlier API version from `dimension`, `metric`, and `vector_type` — report their vector fields under the reserved names `_values` (dense) and `_sparse_values` (sparse), and any metadata fields configured for filtering as legacy fields carrying only `filterable`. Dense vectors-API indexes always report both `_values` and `_sparse_values`, regardless of how they were created.
     * @type {{ [key: string]: IndexSchemaField; }}
     * @memberof IndexSchema
     */
    fields: { [key: string]: IndexSchemaField; };
}

/**
 * Check if a given object implements the IndexSchema interface.
 */
export function instanceOfIndexSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fields" in value;

    return isInstance;
}

export function IndexSchemaFromJSON(json: any): IndexSchema {
    return IndexSchemaFromJSONTyped(json, false);
}

export function IndexSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fields': (mapValues(json['fields'], IndexSchemaFieldFromJSON)),
    };
}

export function IndexSchemaToJSON(value?: IndexSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fields': (mapValues(value.fields, IndexSchemaFieldToJSON)),
    };
}

