/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-07
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataSchemaFieldsValue
 */
export interface MetadataSchemaFieldsValue {
    /**
     * Whether the field is indexed and can be used in filters. Must be present and must be `true`: omitting it, or sending `false` or `null`, is rejected with `Field '<name>' is set to filterable: false. Only filterable: true is supported.` To leave a field unindexed, omit it from `fields` entirely.
     * @type {boolean}
     * @memberof MetadataSchemaFieldsValue
     */
    filterable: boolean;
}

/**
 * Check if a given object implements the MetadataSchemaFieldsValue interface.
 */
export function instanceOfMetadataSchemaFieldsValue(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "filterable" in value;

    return isInstance;
}

export function MetadataSchemaFieldsValueFromJSON(json: any): MetadataSchemaFieldsValue {
    return MetadataSchemaFieldsValueFromJSONTyped(json, false);
}

export function MetadataSchemaFieldsValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataSchemaFieldsValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filterable': json['filterable'],
    };
}

export function MetadataSchemaFieldsValueToJSON(value?: MetadataSchemaFieldsValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filterable': value.filterable,
    };
}

