/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PodBased1Pod } from './PodBased1Pod';
import {
    PodBased1PodFromJSON,
    PodBased1PodFromJSONTyped,
    PodBased1PodToJSON,
} from './PodBased1Pod';

/**
 * 
 * @export
 * @interface PodBased1
 */
export interface PodBased1 {
    /**
     * 
     * @type {PodBased1Pod}
     * @memberof PodBased1
     */
    pod: PodBased1Pod;
}

/**
 * Check if a given object implements the PodBased1 interface.
 */
export function instanceOfPodBased1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pod" in value;

    return isInstance;
}

export function PodBased1FromJSON(json: any): PodBased1 {
    return PodBased1FromJSONTyped(json, false);
}

export function PodBased1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PodBased1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pod': PodBased1PodFromJSON(json['pod']),
    };
}

export function PodBased1ToJSON(value?: PodBased1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pod': PodBased1PodToJSON(value.pod),
    };
}

