/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Updated configuration for pod-based indexes
 * @export
 * @interface PodBased1Pod
 */
export interface PodBased1Pod {
    /**
     * The number of replicas. Replicas duplicate your index. They provide higher availability and throughput. Replicas can be scaled up or down as your needs change.
     * @type {number}
     * @memberof PodBased1Pod
     */
    replicas?: number;
    /**
     * The type of pod to use. One of `s1`, `p1`, or `p2` appended with `.` and one of `x1`, `x2`, `x4`, or `x8`.
     * @type {string}
     * @memberof PodBased1Pod
     */
    podType?: string;
}

/**
 * Check if a given object implements the PodBased1Pod interface.
 */
export function instanceOfPodBased1Pod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PodBased1PodFromJSON(json: any): PodBased1Pod {
    return PodBased1PodFromJSONTyped(json, false);
}

export function PodBased1PodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PodBased1Pod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'replicas': !exists(json, 'replicas') ? undefined : json['replicas'],
        'podType': !exists(json, 'pod_type') ? undefined : json['pod_type'],
    };
}

export function PodBased1PodToJSON(value?: PodBased1Pod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'replicas': value.replicas,
        'pod_type': value.podType,
    };
}

