/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadCapacityOnDemandSpec
 */
export interface ReadCapacityOnDemandSpec {
    /**
     * The mode of the index. Possible values: `OnDemand` or `Dedicated`. Defaults to `OnDemand`. If set to `Dedicated`, `dedicated.node_type`, and `dedicated.scaling` must be specified.
     * @type {string}
     * @memberof ReadCapacityOnDemandSpec
     */
    mode: string;
}

/**
 * Check if a given object implements the ReadCapacityOnDemandSpec interface.
 */
export function instanceOfReadCapacityOnDemandSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "mode" in value;

    return isInstance;
}

export function ReadCapacityOnDemandSpecFromJSON(json: any): ReadCapacityOnDemandSpec {
    return ReadCapacityOnDemandSpecFromJSONTyped(json, false);
}

export function ReadCapacityOnDemandSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadCapacityOnDemandSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mode': json['mode'],
    };
}

export function ReadCapacityOnDemandSpecToJSON(value?: ReadCapacityOnDemandSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mode': value.mode,
    };
}

