/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadCapacityDedicatedConfig } from './ReadCapacityDedicatedConfig';
import {
    ReadCapacityDedicatedConfigFromJSON,
    ReadCapacityDedicatedConfigFromJSONTyped,
    ReadCapacityDedicatedConfigToJSON,
} from './ReadCapacityDedicatedConfig';
import type { ReadCapacityStatus } from './ReadCapacityStatus';
import {
    ReadCapacityStatusFromJSON,
    ReadCapacityStatusFromJSONTyped,
    ReadCapacityStatusToJSON,
} from './ReadCapacityStatus';

/**
 * 
 * @export
 * @interface ReadCapacityDedicatedSpecResponse
 */
export interface ReadCapacityDedicatedSpecResponse {
    /**
     * The mode of the index. Possible values: `OnDemand` or `Dedicated`. Defaults to `OnDemand`. If set to `Dedicated`, `dedicated.node_type`, and `dedicated.scaling` must be specified.
     * @type {string}
     * @memberof ReadCapacityDedicatedSpecResponse
     */
    mode: string;
    /**
     * 
     * @type {ReadCapacityDedicatedConfig}
     * @memberof ReadCapacityDedicatedSpecResponse
     */
    dedicated: ReadCapacityDedicatedConfig;
    /**
     * 
     * @type {ReadCapacityStatus}
     * @memberof ReadCapacityDedicatedSpecResponse
     */
    status: ReadCapacityStatus;
}

/**
 * Check if a given object implements the ReadCapacityDedicatedSpecResponse interface.
 */
export function instanceOfReadCapacityDedicatedSpecResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "mode" in value;
    isInstance = isInstance && "dedicated" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function ReadCapacityDedicatedSpecResponseFromJSON(json: any): ReadCapacityDedicatedSpecResponse {
    return ReadCapacityDedicatedSpecResponseFromJSONTyped(json, false);
}

export function ReadCapacityDedicatedSpecResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadCapacityDedicatedSpecResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'dedicated': ReadCapacityDedicatedConfigFromJSON(json['dedicated']),
        'status': ReadCapacityStatusFromJSON(json['status']),
    };
}

export function ReadCapacityDedicatedSpecResponseToJSON(value?: ReadCapacityDedicatedSpecResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mode': value.mode,
        'dedicated': ReadCapacityDedicatedConfigToJSON(value.dedicated),
        'status': ReadCapacityStatusToJSON(value.status),
    };
}

