/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-10
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaginationResponse } from './PaginationResponse';
import {
    PaginationResponseFromJSON,
    PaginationResponseFromJSONTyped,
    PaginationResponseToJSON,
} from './PaginationResponse';
import type { RestoreJobModel } from './RestoreJobModel';
import {
    RestoreJobModelFromJSON,
    RestoreJobModelFromJSONTyped,
    RestoreJobModelToJSON,
} from './RestoreJobModel';

/**
 * The list of restore jobs that exist in the project.
 * @export
 * @interface RestoreJobList
 */
export interface RestoreJobList {
    /**
     * List of restore job objects
     * @type {Array<RestoreJobModel>}
     * @memberof RestoreJobList
     */
    data: Array<RestoreJobModel>;
    /**
     * 
     * @type {PaginationResponse}
     * @memberof RestoreJobList
     */
    pagination?: PaginationResponse;
}

/**
 * Check if a given object implements the RestoreJobList interface.
 */
export function instanceOfRestoreJobList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function RestoreJobListFromJSON(json: any): RestoreJobList {
    return RestoreJobListFromJSONTyped(json, false);
}

export function RestoreJobListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestoreJobList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(RestoreJobModelFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : PaginationResponseFromJSON(json['pagination']),
    };
}

export function RestoreJobListToJSON(value?: RestoreJobList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(RestoreJobModelToJSON)),
        'pagination': PaginationResponseToJSON(value.pagination),
    };
}

