/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-04
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadCapacity } from './ReadCapacity';
import {
    ReadCapacityFromJSON,
    ReadCapacityFromJSONTyped,
    ReadCapacityToJSON,
} from './ReadCapacity';

/**
 * Updated configuration for serverless indexes
 * @export
 * @interface ServerlessServerless
 */
export interface ServerlessServerless {
    /**
     * 
     * @type {ReadCapacity}
     * @memberof ServerlessServerless
     */
    readCapacity?: ReadCapacity;
}

/**
 * Check if a given object implements the ServerlessServerless interface.
 */
export function instanceOfServerlessServerless(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServerlessServerlessFromJSON(json: any): ServerlessServerless {
    return ServerlessServerlessFromJSONTyped(json, false);
}

export function ServerlessServerlessFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerlessServerless {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'readCapacity': !exists(json, 'read_capacity') ? undefined : ReadCapacityFromJSON(json['read_capacity']),
    };
}

export function ServerlessServerlessToJSON(value?: ServerlessServerless | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'read_capacity': ReadCapacityToJSON(value.readCapacity),
    };
}

