/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-07
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateEmbedConfig } from './CreateEmbedConfig';
import {
    CreateEmbedConfigFromJSON,
    CreateEmbedConfigFromJSONTyped,
    CreateEmbedConfigToJSON,
} from './CreateEmbedConfig';
import type { CreateSparseEmbedConfig } from './CreateSparseEmbedConfig';
import {
    CreateSparseEmbedConfigFromJSON,
    CreateSparseEmbedConfigFromJSONTyped,
    CreateSparseEmbedConfigToJSON,
} from './CreateSparseEmbedConfig';
import type { StringFieldFullTextSearch } from './StringFieldFullTextSearch';
import {
    StringFieldFullTextSearchFromJSON,
    StringFieldFullTextSearchFromJSONTyped,
    StringFieldFullTextSearchToJSON,
} from './StringFieldFullTextSearch';

/**
 * A string field configuration. The field must declare at least one search configuration:
 * 
 * - `full_text_search`: Index the text for full-text search.
 * - `embed`: Integrated embedding with a dense model. Pinecone embeds the text with a hosted dense embedding model.
 * - `sparse_embed`: Integrated embedding with a sparse model. Pinecone embeds the text with a hosted sparse embedding model.
 * 
 * They can be combined on one field, so the same text can be searched by full-text search, dense similarity, and sparse similarity. A string field with none of them is a metadata field and is rejected; include metadata in the documents you upsert instead.
 * 
 * By default the field's text is stored, and a stored field is always indexed for full-text search: when `full_text_search` is omitted, it is enabled with default settings. Set `store_text` to `false` to embed the text without storing it.
 * 
 * Each value is at most 100 KB, whether or not the text is stored.
 * @export
 * @interface StringField
 */
export interface StringField {
    /**
     * Identifies this as a string field. Must be `string`.
     * @type {string}
     * @memberof StringField
     */
    type: StringFieldTypeEnum;
    /**
     * Optional description for this field, at most 256 bytes.
     * @type {string}
     * @memberof StringField
     */
    description?: string;
    /**
     * 
     * @type {StringFieldFullTextSearch}
     * @memberof StringField
     */
    fullTextSearch?: StringFieldFullTextSearch;
    /**
     * When `true` (the default), the field's text is stored and the field is indexed for full-text search. Each value is then subject to the full-text limit of 10,000 tokens after tokenization, in addition to the 100 KB limit.
     * 
     * When `false`, the field's text is embedded and then discarded rather than stored. Such a field must declare `embed` or `sparse_embed`, and cannot declare `full_text_search`. A fetch or search whose `include_fields` names it is rejected with `400`, and it cannot be scored with `text` or `query_string` or matched with `$match_phrase`, `$match_all`, or `$match_any`; searching it with an `embed` or `sparse_embed` scoring method still works.
     * 
     * Fixed at creation.
     * @type {boolean}
     * @memberof StringField
     */
    storeText?: boolean;
    /**
     * 
     * @type {CreateEmbedConfig}
     * @memberof StringField
     */
    embed?: CreateEmbedConfig;
    /**
     * 
     * @type {CreateSparseEmbedConfig}
     * @memberof StringField
     */
    sparseEmbed?: CreateSparseEmbedConfig;
}


/**
 * @export
 */
export const StringFieldTypeEnum = {
    String: 'string'
} as const;
export type StringFieldTypeEnum = typeof StringFieldTypeEnum[keyof typeof StringFieldTypeEnum];


/**
 * Check if a given object implements the StringField interface.
 */
export function instanceOfStringField(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function StringFieldFromJSON(json: any): StringField {
    return StringFieldFromJSONTyped(json, false);
}

export function StringFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'fullTextSearch': !exists(json, 'full_text_search') ? undefined : StringFieldFullTextSearchFromJSON(json['full_text_search']),
        'storeText': !exists(json, 'store_text') ? undefined : json['store_text'],
        'embed': !exists(json, 'embed') ? undefined : CreateEmbedConfigFromJSON(json['embed']),
        'sparseEmbed': !exists(json, 'sparse_embed') ? undefined : CreateSparseEmbedConfigFromJSON(json['sparse_embed']),
    };
}

export function StringFieldToJSON(value?: StringField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'description': value.description,
        'full_text_search': StringFieldFullTextSearchToJSON(value.fullTextSearch),
        'store_text': value.storeText,
        'embed': CreateEmbedConfigToJSON(value.embed),
        'sparse_embed': CreateSparseEmbedConfigToJSON(value.sparseEmbed),
    };
}

