/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Inference API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelInfoMetric } from './ModelInfoMetric';
import {
    ModelInfoMetricFromJSON,
    ModelInfoMetricFromJSONTyped,
    ModelInfoMetricToJSON,
} from './ModelInfoMetric';
import type { ModelInfoSupportedParameter } from './ModelInfoSupportedParameter';
import {
    ModelInfoSupportedParameterFromJSON,
    ModelInfoSupportedParameterFromJSONTyped,
    ModelInfoSupportedParameterToJSON,
} from './ModelInfoSupportedParameter';

/**
 * Represents the model configuration including model type, supported parameters, and other model details.
 * @export
 * @interface ModelInfo
 */
export interface ModelInfo {
    /**
     * The name of the model.
     * @type {string}
     * @memberof ModelInfo
     */
    name: string;
    /**
     * A summary of the model.
     * @type {string}
     * @memberof ModelInfo
     */
    shortDescription: string;
    /**
     * The type of model (e.g. 'embed' or 'rerank').
     * @type {string}
     * @memberof ModelInfo
     */
    type: ModelInfoTypeEnum;
    /**
     * Whether the embedding model produces 'dense' or 'sparse' embeddings.
     * @type {string}
     * @memberof ModelInfo
     */
    vectorType?: ModelInfoVectorTypeEnum;
    /**
     * The embedding model dimension (applies to dense embedding models only).
     * @type {number}
     * @memberof ModelInfo
     */
    dimension?: number;
    /**
     * The modality of the model (e.g. 'text').
     * @type {string}
     * @memberof ModelInfo
     */
    modality?: string;
    /**
     * The maximum tokens per sequence supported by the model.
     * @type {number}
     * @memberof ModelInfo
     */
    sequenceLength?: number;
    /**
     * The maximum batch size (number of sequences) supported by the model.
     * @type {number}
     * @memberof ModelInfo
     */
    batchSize?: number;
    /**
     * The distance metrics supported by the model for similarity search.
     * @type {Array<ModelInfoMetric>}
     * @memberof ModelInfo
     */
    supportedMetrics?: Array<ModelInfoMetric>;
    /**
     * 
     * @type {Array<ModelInfoSupportedParameter>}
     * @memberof ModelInfo
     */
    supportedParameters: Array<ModelInfoSupportedParameter>;
}


/**
 * @export
 */
export const ModelInfoTypeEnum = {
    Embed: 'embed',
    Rerank: 'rerank'
} as const;
export type ModelInfoTypeEnum = typeof ModelInfoTypeEnum[keyof typeof ModelInfoTypeEnum];

/**
 * @export
 */
export const ModelInfoVectorTypeEnum = {
    Dense: 'dense',
    Sparse: 'sparse'
} as const;
export type ModelInfoVectorTypeEnum = typeof ModelInfoVectorTypeEnum[keyof typeof ModelInfoVectorTypeEnum];


/**
 * Check if a given object implements the ModelInfo interface.
 */
export function instanceOfModelInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "shortDescription" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "supportedParameters" in value;

    return isInstance;
}

export function ModelInfoFromJSON(json: any): ModelInfo {
    return ModelInfoFromJSONTyped(json, false);
}

export function ModelInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'shortDescription': json['short_description'],
        'type': json['type'],
        'vectorType': !exists(json, 'vector_type') ? undefined : json['vector_type'],
        'dimension': !exists(json, 'dimension') ? undefined : json['dimension'],
        'modality': !exists(json, 'modality') ? undefined : json['modality'],
        'sequenceLength': !exists(json, 'sequence_length') ? undefined : json['sequence_length'],
        'batchSize': !exists(json, 'batch_size') ? undefined : json['batch_size'],
        'supportedMetrics': !exists(json, 'supported_metrics') ? undefined : ((json['supported_metrics'] as Array<any>).map(ModelInfoMetricFromJSON)),
        'supportedParameters': ((json['supported_parameters'] as Array<any>).map(ModelInfoSupportedParameterFromJSON)),
    };
}

export function ModelInfoToJSON(value?: ModelInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'short_description': value.shortDescription,
        'type': value.type,
        'vector_type': value.vectorType,
        'dimension': value.dimension,
        'modality': value.modality,
        'sequence_length': value.sequenceLength,
        'batch_size': value.batchSize,
        'supported_metrics': value.supportedMetrics === undefined ? undefined : ((value.supportedMetrics as Array<any>).map(ModelInfoMetricToJSON)),
        'supported_parameters': ((value.supportedParameters as Array<any>).map(ModelInfoSupportedParameterToJSON)),
    };
}

