/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Inference API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-01
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Usage statistics for the model inference.
 * @export
 * @interface RerankResultUsage
 */
export interface RerankResultUsage {
    /**
     * The number of rerank units consumed by this operation.
     * @type {number}
     * @memberof RerankResultUsage
     */
    rerankUnits?: number;
}

/**
 * Check if a given object implements the RerankResultUsage interface.
 */
export function instanceOfRerankResultUsage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RerankResultUsageFromJSON(json: any): RerankResultUsage {
    return RerankResultUsageFromJSONTyped(json, false);
}

export function RerankResultUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RerankResultUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rerankUnits': !exists(json, 'rerank_units') ? undefined : json['rerank_units'],
    };
}

export function RerankResultUsageToJSON(value?: RerankResultUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rerank_units': value.rerankUnits,
    };
}

