// Class, function exports
export { Pinecone } from './pinecone';
export { Index } from './data';
export { Inference } from './inference';
export { Assistant, ChatStream } from './assistant';
export * as Errors from './errors';

// Interface exports
export type { RerankOptions, ListModelsOptions } from './inference';
export type {
  RerankResult,
  RerankResultUsage,
  RankedDocument,
  EmbeddingsList,
  EmbeddingsListUsage,
  Embedding,
  ModelInfo,
  ModelInfoList,
} from './pinecone-generated-ts-fetch/inference';
export type {
  ImportModel,
  ListResponse,
  ListNamespacesResponse,
  NamespaceDescription,
  SearchRecordsResponse,
  SearchRecordsResponseResult,
  SearchUsage,
  StartImportResponse,
} from './pinecone-generated-ts-fetch/db_data';
export type {
  AssistantList,
  AssistantModel,
  AssistantStatusEnum,
  ChatOptions,
  ChatContextOptions,
  ChatCompletionOptions,
  ChatModelEnum,
  ChoiceModel,
  FinishReasonEnum,
  StreamedChatResponse,
  StreamedChatCompletionResponse,
  BaseChunk,
  MessageStartChunk,
  ContentChunk,
  CitationChunk,
  MessageEndChunk,
  ContextOptions,
  AssistantFileModel,
  AssistantFileStatusEnum,
  AssistantFilesList,
  ListFilesOptions,
  UploadFileOptions,
  CreateAssistantOptions,
  UpdateAssistantOptions,
  UpdateAssistantResponse,
} from './assistant';
export type {
  ChatModel,
  ChatCompletionModel,
  CitationModel,
  ContextModel,
  HighlightModel,
  MessageModel,
  UsageModel,
} from './pinecone-generated-ts-fetch/assistant_data';

// Type exports
export type {
  BackupId,
  RestoreJobId,
  CollectionName,
  CreateBackupOptions,
  CreateIndexFromBackupOptions,
  DescribeBackupOptions,
  DescribeRestoreJobOptions,
  ListRestoreJobsOptions,
  DeleteBackupOptions,
  CreateIndexOptions,
  CreateIndexSpec,
  CreateIndexServerlessSpec,
  CreateIndexPodSpec,
  CreateIndexByocSpec,
  CreateIndexReadCapacity,
  DedicatedNodeType,
  ReadCapacityOnDemandParams,
  ReadCapacityDedicatedParams,
  ConfigureIndexOptions,
  CreateIndexForModelOptions,
  CreateIndexForModelEmbed,
  DeleteCollectionOptions,
  DeleteIndexOptions,
  DescribeIndexOptions,
  DescribeCollectionOptions,
  IndexName,
  ListBackupsOptions,
  PodType,
} from './control';
export type { IndexOptions, AssistantOptions } from './types';
export type {
  CreateNamespaceOptions,
  DeleteManyByFilterOptions,
  DeleteManyByRecordIdOptions,
  DeleteManyOptions,
  DeleteOneOptions,
  DescribeIndexStatsOptions,
  FetchOptions,
  FetchResponse,
  IndexStatsDescription,
  IndexStatsNamespaceSummary,
  IntegratedRecord,
  PineconeConfiguration,
  PineconeRecord,
  UpdateOptions,
  QueryByRecordId,
  QueryByVectorValues,
  QueryOptions,
  QueryResponse,
  QueryShared,
  RecordId,
  RecordMetadata,
  RecordMetadataValue,
  RecordSparseValues,
  RecordValues,
  ScoredPineconeRecord,
} from './data';
export type {
  BackupList,
  BackupModel,
  ByocSpec,
  CollectionList,
  CollectionModel,
  ConfigureIndexRequestSpec,
  ConfigureIndexRequestEmbed,
  CreateCollectionRequest,
  CreateIndexForModelRequest,
  CreateIndexFromBackupResponse,
  CreateIndexRequest,
  DescribeCollectionRequest,
  DescribeIndexRequest,
  FetchAPI,
  IndexList,
  IndexModel,
  MetadataSchema,
  MetadataSchemaFieldsValue,
  PodSpec,
  PodSpecMetadataConfig,
  ReadCapacity,
  ReadCapacityDedicatedConfig,
  ReadCapacityDedicatedSpec,
  ReadCapacityDedicatedSpecResponse,
  ReadCapacityOnDemandSpec,
  ReadCapacityOnDemandSpecResponse,
  ReadCapacityStatus,
  RestoreJobList,
  RestoreJobModel,
  ServerlessSpec,
} from './pinecone-generated-ts-fetch/db_control';
