// Class, function exports
export { Pinecone } from './pinecone';
export { Index } from './data';
export { Inference } from './inference';
export { Assistant, ChatStream } from './assistant';
export * as Errors from './errors';

// Interface exports
export type {
  RerankOptions,
  ListModelsOptions,
  EmbedOptions,
} from './inference';
export type {
  RerankResult,
  RerankResultUsage,
  RankedDocument,
  EmbeddingsList,
  EmbeddingsListUsage,
  Embedding,
  ModelInfo,
  ModelInfoList,
} from './pinecone-generated-ts-fetch/inference';
export type {
  HTTPHeaders,
  Hit,
  ImportModel,
  ImportErrorMode,
  ListImportsResponse,
  ListResponse,
  ListNamespacesResponse,
  Pagination,
  NamespaceDescription,
  CreateNamespaceRequestSchema,
  CreateNamespaceRequestSchemaFieldsValue,
  NamespaceDescriptionIndexedFields,
  SearchRecordsResponse,
  SearchRecordsResponseResult,
  SearchUsage,
  StartImportResponse,
} from './pinecone-generated-ts-fetch/db_data';
export type {
  CreateAssistantOptions,
  UpdateAssistantOptions,
  UpdateAssistantResponse,
  AssistantList,
  AssistantModel,
  EvaluateOptions,
  ChatOptions,
  ChatContextOptions,
  ChatCompletionOptions,
  ContextOptions,
  ListFilesOptions,
  UploadFileOptions,
  AssistantFilesList,
  MessagesModel,
  MessageModel,
  ChatModelEnum,
  ChoiceModel,
  FinishReasonEnum,
  StreamedChatResponse,
  StreamedChatCompletionResponse,
  BaseChunk,
  MessageStartChunk,
  ContentChunk,
  CitationChunk,
  MessageEndChunk,
} from './assistant';
export type {
  ChatModel,
  ChatCompletionModel,
  CitationModel,
  ContextModel,
  HighlightModel,
  ImageModel,
  MultiModalContentBlocksModel,
  MultiModalContentImageBlockModel,
  MultiModalContentTextBlockModel,
  MultiModalSnippetModel,
  ReferenceModel,
  SnippetModel,
  TextReferenceModel,
  TextSnippetModel,
  TypedReferenceModel,
  UsageModel,
  PdfReferenceModel,
  DocxReferenceModel,
  JsonReferenceModel,
  MarkdownReferenceModel,
  AssistantFileModel,
} from './pinecone-generated-ts-fetch/assistant_data';
export type {
  AlignmentResponse,
  Metrics,
  Reasoning,
  EvaluatedFact,
  Fact,
  TokenCounts,
} from './pinecone-generated-ts-fetch/assistant_evaluation';

// Type exports
export type {
  BackupId,
  RestoreJobId,
  CollectionName,
  CreateBackupOptions,
  CreateIndexFromBackupOptions,
  DescribeBackupOptions,
  DescribeRestoreJobOptions,
  ListRestoreJobsOptions,
  DeleteBackupOptions,
  CreateIndexOptions,
  CreateIndexSpec,
  CreateIndexServerlessSpec,
  CreateIndexPodSpec,
  CreateIndexByocSpec,
  CreateIndexReadCapacity,
  DedicatedNodeType,
  ReadCapacityOnDemandParams,
  ReadCapacityDedicatedParams,
  ConfigureIndexOptions,
  CreateIndexForModelOptions,
  CreateIndexForModelEmbed,
  DeleteCollectionOptions,
  DeleteIndexOptions,
  DescribeIndexOptions,
  DescribeCollectionOptions,
  IndexName,
  ListBackupsOptions,
  PodType,
} from './control';
export type { IndexOptions, AssistantOptions } from './types';
export type {
  CreateNamespaceOptions,
  DeleteAllOptions,
  DeleteManyOptions,
  DeleteOneOptions,
  DescribeIndexStatsOptions,
  FetchOptions,
  FetchResponse,
  FetchByMetadataOptions,
  FetchByMetadataResponse,
  IndexStatsDescription,
  IndexStatsNamespaceSummary,
  IntegratedRecord,
  ListOptions,
  ListNamespacesOptions,
  OperationUsage,
  PineconeConfiguration,
  PineconeRecord,
  UpdateOptions,
  UpsertOptions,
  UpsertRecordsOptions,
  QueryByRecordId,
  QueryByVectorValues,
  QueryOptions,
  QueryResponse,
  QueryShared,
  RecordId,
  RecordMetadata,
  RecordMetadataValue,
  RecordSparseValues,
  RecordValues,
  ScoredPineconeRecord,
  SearchRecordsOptions,
  SearchRecordsQuery,
  SearchRecordsRerank,
  SearchRecordsVector,
  StartImportOptions,
} from './data';
export type {
  BackupList,
  BackupModel,
  ByocSpec,
  CollectionList,
  CollectionModel,
  ConfigureIndexRequestSpec,
  ConfigureIndexRequestEmbed,
  CreateCollectionRequest,
  CreateIndexForModelRequest,
  CreateIndexFromBackupResponse,
  CreateIndexRequest,
  DescribeCollectionRequest,
  DescribeIndexRequest,
  FetchAPI,
  IndexList,
  IndexModel,
  MetadataSchema,
  MetadataSchemaFieldsValue,
  PodSpec,
  PodSpecMetadataConfig,
  ReadCapacity,
  ReadCapacityDedicatedConfig,
  ReadCapacityDedicatedSpec,
  ReadCapacityDedicatedSpecResponse,
  ReadCapacityOnDemandSpec,
  ReadCapacityOnDemandSpecResponse,
  ReadCapacityStatus,
  RestoreJobList,
  RestoreJobModel,
  ServerlessSpec,
} from './pinecone-generated-ts-fetch/db_control';
