name: 'integration tests'
description: 'Run integration tests'
inputs:
  pinecone_api_key:
    description: 'API key'
    required: true
  pinecone_environment:
    description: 'Environment/region to target'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run tests
      env:
        CI: true
        PINECONE_API_KEY: ${{ inputs.pinecone_api_key }}
        PINECONE_ENVIRONMENT: ${{ inputs.pinecone_environment }}
      run: npm run test
      shell: bash