import type {
  ManageIndexesApi,
  IndexModel,
  ManagedDeployment,
} from '../../pinecone-generated-ts-fetch-alpha/db_control';
import { X_PINECONE_API_VERSION } from '../../pinecone-generated-ts-fetch-alpha/db_control';
import { PineconeArgumentError } from '../../errors';
import { handleApiError } from '../../errors/handling';

/**
 * Options for {@link PreviewIndexes.createIndexForModel} using the 2026-01.alpha API.
 *
 * The embedding model determines dimension and default metric; callers supply `field`,
 * `model`, `cloud`, and `region` at minimum.
 *
 * **Alpha notice:** This type is not covered by the SDK's backward compatibility guarantee.
 *
 * @see [Model-based indexes](https://docs.pinecone.io/guides/index-data/create-an-index)
 * @alpha
 */
export interface PreviewCreateIndexForModelOptions {
  /** The name of the index. Auto-generated by the service if omitted. */
  name?: string;
  /** Cloud provider — `"aws"` | `"gcp"` | `"azure"`. */
  cloud: string;
  /** Cloud region (e.g. `"us-east-1"`). */
  region: string;
  /**
   * The name of the schema field that will hold the embedded text.
   * This becomes a `semantic_text` field in the index schema.
   */
  field: string;
  /**
   * The name of the embedding model to use (e.g. `"multilingual-e5-large"`).
   * Refer to the model guide for available models.
   */
  model: string;
  /**
   * Distance metric override. Defaults to the model's recommended metric.
   * One of `"cosine"` | `"euclidean"` | `"dotproduct"`.
   */
  metric?: string;
  /** Model-specific parameters applied when embedding documents at write time. */
  writeParameters?: object;
  /** Model-specific parameters applied when embedding queries at read time. */
  readParameters?: object;
  /** Enable or disable deletion protection. */
  deletionProtection?: 'enabled' | 'disabled';
  /** User-defined metadata tags for the index. */
  tags?: { [key: string]: string };
}

/**
 * Creates a model-configured serverless index using the 2026-01.alpha API.
 *
 * The embedding model determines dimension and default metric; callers do not
 * supply them explicitly.
 *
 * **Alpha notice:** This function is not covered by the SDK's backward compatibility
 * guarantee. Signatures may change without a major version bump.
 *
 * @see [Model-based indexes](https://docs.pinecone.io/guides/index-data/create-an-index)
 * @alpha
 */
export async function createIndexForModel(
  api: ManageIndexesApi,
  options: PreviewCreateIndexForModelOptions,
): Promise<IndexModel> {
  if (!options.cloud) {
    throw new PineconeArgumentError(
      'You must pass a non-empty string for `cloud` in order to create an index for a model.',
    );
  }
  if (!options.region) {
    throw new PineconeArgumentError(
      'You must pass a non-empty string for `region` in order to create an index for a model.',
    );
  }
  if (!options.field) {
    throw new PineconeArgumentError(
      'You must pass a non-empty string for `field` in order to create an index for a model.',
    );
  }
  if (!options.model) {
    throw new PineconeArgumentError(
      'You must pass a non-empty string for `model` in order to create an index for a model.',
    );
  }

  const deployment: ManagedDeployment = {
    deployment_type: 'managed',
    cloud: options.cloud,
    region: options.region,
  };

  try {
    return await api.createIndexForModel({
      createIndexForModelRequest: {
        name: options.name,
        deployment,
        field: options.field,
        model: options.model,
        metric: options.metric,
        write_parameters: options.writeParameters,
        read_parameters: options.readParameters,
        deletion_protection: options.deletionProtection,
        tags: options.tags,
      },
      xPineconeApiVersion: X_PINECONE_API_VERSION,
    });
  } catch (e) {
    throw await handleApiError(
      e,
      async (_, rawMessageText) =>
        `Error creating preview index for model ${options.model}: ${rawMessageText}`,
    );
  }
}
