/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-01.alpha
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ManagedDeployment } from './ManagedDeployment';
import {
    ManagedDeploymentFromJSON,
    ManagedDeploymentFromJSONTyped,
    ManagedDeploymentToJSON,
} from './ManagedDeployment';
import type { ReadCapacity } from './ReadCapacity';
import {
    ReadCapacityFromJSON,
    ReadCapacityFromJSONTyped,
    ReadCapacityToJSON,
} from './ReadCapacity';

/**
 * Configuration for creating an index with an integrated embedding model. The server constructs a `semantic_text` schema field named `field` using the provided model parameters.
 * @export
 * @interface CreateIndexForModelRequest
 */
export interface CreateIndexForModelRequest {
    /**
     * The name of the index. Auto-generated if not provided. Resource name must be 1-45 characters long, start and end with an alphanumeric character, and consist only of lower case alphanumeric characters or '-'. Callers that require retry-safe behavior should provide an explicit name — a duplicate request with the same name returns 409, making success detectable on retry.
     * @type {string}
     * @memberof CreateIndexForModelRequest
     */
    name?: string;
    /**
     * 
     * @type {ManagedDeployment}
     * @memberof CreateIndexForModelRequest
     */
    deployment?: ManagedDeployment;
    /**
     * The name of the schema field that will hold the embedded text. This becomes a `semantic_text` field in the index schema.
     * @type {string}
     * @memberof CreateIndexForModelRequest
     */
    field: string;
    /**
     * The name of the embedding model to use. Refer to the [model guide](https://docs.pinecone.io/guides/index-data/create-an-index#embedding-models) for available models and details.
     * @type {string}
     * @memberof CreateIndexForModelRequest
     */
    model: string;
    /**
     * The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector_type' is 'sparse', the metric must be 'dotproduct'. If the `vector_type` is `dense`, the metric defaults to 'cosine'.
     * Possible values: `cosine`, `euclidean`, or `dotproduct`.
     * @type {string}
     * @memberof CreateIndexForModelRequest
     */
    metric?: string;
    /**
     * Model-specific parameters applied when embedding documents at write time.
     * @type {object}
     * @memberof CreateIndexForModelRequest
     */
    writeParameters?: object;
    /**
     * Model-specific parameters applied when embedding queries at read time.
     * @type {object}
     * @memberof CreateIndexForModelRequest
     */
    readParameters?: object;
    /**
     * 
     * @type {ReadCapacity}
     * @memberof CreateIndexForModelRequest
     */
    readCapacity?: ReadCapacity;
    /**
     * Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '_', or '-'.  Values must be alphanumeric, ';', '@', '_', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
     * @type {{ [key: string]: string; }}
     * @memberof CreateIndexForModelRequest
     */
    tags?: { [key: string]: string; };
    /**
     * Whether [deletion protection](http://docs.pinecone.io/guides/manage-data/manage-indexes#configure-deletion-protection) is enabled/disabled for the index.
     * Possible values: `disabled` or `enabled`.
     * @type {string}
     * @memberof CreateIndexForModelRequest
     */
    deletionProtection?: string;
}

/**
 * Check if a given object implements the CreateIndexForModelRequest interface.
 */
export function instanceOfCreateIndexForModelRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "field" in value;
    isInstance = isInstance && "model" in value;

    return isInstance;
}

export function CreateIndexForModelRequestFromJSON(json: any): CreateIndexForModelRequest {
    return CreateIndexForModelRequestFromJSONTyped(json, false);
}

export function CreateIndexForModelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIndexForModelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'deployment': !exists(json, 'deployment') ? undefined : ManagedDeploymentFromJSON(json['deployment']),
        'field': json['field'],
        'model': json['model'],
        'metric': !exists(json, 'metric') ? undefined : json['metric'],
        'writeParameters': !exists(json, 'write_parameters') ? undefined : json['write_parameters'],
        'readParameters': !exists(json, 'read_parameters') ? undefined : json['read_parameters'],
        'readCapacity': !exists(json, 'read_capacity') ? undefined : ReadCapacityFromJSON(json['read_capacity']),
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'deletionProtection': !exists(json, 'deletion_protection') ? undefined : json['deletion_protection'],
    };
}

export function CreateIndexForModelRequestToJSON(value?: CreateIndexForModelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'deployment': ManagedDeploymentToJSON(value.deployment),
        'field': value.field,
        'model': value.model,
        'metric': value.metric,
        'write_parameters': value.writeParameters,
        'read_parameters': value.readParameters,
        'read_capacity': ReadCapacityToJSON(value.readCapacity),
        'tags': value.tags,
        'deletion_protection': value.deletionProtection,
    };
}

