/* tslint:disable */
/* eslint-disable */
/**
 * Pinecone Control Plane API
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2026-01.alpha
 * Contact: support@pinecone.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BooleanField,
    instanceOfBooleanField,
    BooleanFieldFromJSON,
    BooleanFieldFromJSONTyped,
    BooleanFieldToJSON,
} from './BooleanField';
import {
    DenseVectorField,
    instanceOfDenseVectorField,
    DenseVectorFieldFromJSON,
    DenseVectorFieldFromJSONTyped,
    DenseVectorFieldToJSON,
} from './DenseVectorField';
import {
    FloatField,
    instanceOfFloatField,
    FloatFieldFromJSON,
    FloatFieldFromJSONTyped,
    FloatFieldToJSON,
} from './FloatField';
import {
    IntegerField,
    instanceOfIntegerField,
    IntegerFieldFromJSON,
    IntegerFieldFromJSONTyped,
    IntegerFieldToJSON,
} from './IntegerField';
import {
    ResponseStringField,
    instanceOfResponseStringField,
    ResponseStringFieldFromJSON,
    ResponseStringFieldFromJSONTyped,
    ResponseStringFieldToJSON,
} from './ResponseStringField';
import {
    SemanticTextField,
    instanceOfSemanticTextField,
    SemanticTextFieldFromJSON,
    SemanticTextFieldFromJSONTyped,
    SemanticTextFieldToJSON,
} from './SemanticTextField';
import {
    SparseVectorField,
    instanceOfSparseVectorField,
    SparseVectorFieldFromJSON,
    SparseVectorFieldFromJSONTyped,
    SparseVectorFieldToJSON,
} from './SparseVectorField';
import {
    StringListField,
    instanceOfStringListField,
    StringListFieldFromJSON,
    StringListFieldFromJSONTyped,
    StringListFieldToJSON,
} from './StringListField';

/**
 * @type TypedIndexSchemaField
 * A schema field that carries a `type` discriminator. This covers all field types in current use. See `IndexSchemaField` for the full union that also includes legacy untyped fields.
 * @export
 */
export type TypedIndexSchemaField = { type: 'boolean' } & BooleanField | { type: 'dense_vector' } & DenseVectorField | { type: 'float' } & FloatField | { type: 'integer' } & IntegerField | { type: 'semantic_text' } & SemanticTextField | { type: 'sparse_vector' } & SparseVectorField | { type: 'string' } & ResponseStringField | { type: 'string_list' } & StringListField;

export function TypedIndexSchemaFieldFromJSON(json: any): TypedIndexSchemaField {
    return TypedIndexSchemaFieldFromJSONTyped(json, false);
}

export function TypedIndexSchemaFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedIndexSchemaField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'boolean':
            return {...BooleanFieldFromJSONTyped(json, true), type: 'boolean'};
        case 'dense_vector':
            return {...DenseVectorFieldFromJSONTyped(json, true), type: 'dense_vector'};
        case 'float':
            return {...FloatFieldFromJSONTyped(json, true), type: 'float'};
        case 'integer':
            return {...IntegerFieldFromJSONTyped(json, true), type: 'integer'};
        case 'semantic_text':
            return {...SemanticTextFieldFromJSONTyped(json, true), type: 'semantic_text'};
        case 'sparse_vector':
            return {...SparseVectorFieldFromJSONTyped(json, true), type: 'sparse_vector'};
        case 'string':
            return {...ResponseStringFieldFromJSONTyped(json, true), type: 'string'};
        case 'string_list':
            return {...StringListFieldFromJSONTyped(json, true), type: 'string_list'};
        default:
            throw new Error(`No variant of TypedIndexSchemaField exists with 'type=${json['type']}'`);
    }
}

export function TypedIndexSchemaFieldToJSON(value?: TypedIndexSchemaField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'boolean':
            return BooleanFieldToJSON(value);
        case 'dense_vector':
            return DenseVectorFieldToJSON(value);
        case 'float':
            return FloatFieldToJSON(value);
        case 'integer':
            return IntegerFieldToJSON(value);
        case 'semantic_text':
            return SemanticTextFieldToJSON(value);
        case 'sparse_vector':
            return SparseVectorFieldToJSON(value);
        case 'string':
            return ResponseStringFieldToJSON(value);
        case 'string_list':
            return StringListFieldToJSON(value);
        default:
            throw new Error(`No variant of TypedIndexSchemaField exists with 'type=${value['type']}'`);
    }

}

