name: 'Merge to main'

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-publish-docs:
    name: Build and publish docs to sdk-docs
    uses: ./.github/workflows/build-and-publish-docs.yml
    secrets: inherit
