name: 'Cleanup test resources'

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  cleanup:
    name: Delete all indexes and collections in sdk-node-testing project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Cleanup
        run: npm run test:integration:cleanup
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
